from converter.spiders.base_classes.csv_base import CSVBase
from converter.spiders.base_classes.edu_sharing_base import EduSharingBase
from converter.spiders.base_classes.json_base import JSONBase
from converter.spiders.base_classes.lernprogramme_spider_base import LernprogrammeSpiderBase
from converter.spiders.base_classes.lom_base import LomBase
from converter.spiders.base_classes.lrmi_base import LrmiBase
from converter.spiders.base_classes.oai_base import OAIBase
from converter.spiders.base_classes.rss_base import RSSBase
from converter.spiders.base_classes.rss_list_base import RSSListBase
from converter.spiders.base_classes.mediawiki_base import MediaWikiBase
