from parsel import Selector as _ParselSelector
from scrapy.utils.trackref import object_ref
from typing import Any, Optional

class SelectorList(_ParselSelector.selectorlist_cls, object_ref): ...

class Selector(_ParselSelector, object_ref):
    selectorlist_cls: Any = ...
    response: Any = ...
    def __init__(self, response: Optional[Any] = ..., text: Optional[Any] = ..., type: Optional[Any] = ..., root: Optional[Any] = ..., **kwargs: Any) -> None: ...
