from scrapy.core.downloader.tls import DEFAULT_CIPHERS as DEFAULT_CIPHERS, ScrapyClientTLSOptions as ScrapyClientTLSOptions
from twisted.web.client import BrowserLikePolicyForHTTPS
from typing import Any, Optional

class ScrapyClientContextFactory(BrowserLikePolicyForHTTPS):
    tls_verbose_logging: Any = ...
    tls_ciphers: Any = ...
    def __init__(self, method: Any = ..., tls_verbose_logging: bool = ..., tls_ciphers: Optional[Any] = ..., *args: Any, **kwargs: Any) -> None: ...
    @classmethod
    def from_settings(cls, settings: Any, method: Any = ..., *args: Any, **kwargs: Any): ...
    def getCertificateOptions(self): ...
    def getContext(self, hostname: Optional[Any] = ..., port: Optional[Any] = ...): ...
    def creatorForNetloc(self, hostname: Any, port: Any): ...

class BrowserLikeContextFactory(ScrapyClientContextFactory):
    def creatorForNetloc(self, hostname: Any, port: Any): ...
