# coding: utf-8

"""
    edu-sharing Repository REST API

    The public restful API of the edu-sharing repository.

    The version of the OpenAPI document: 1.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class HomeFolderOptions(BaseModel):
    """
    HomeFolderOptions
    """ # noqa: E501
    folders: Optional[StrictStr] = None
    private_files: Optional[StrictStr] = Field(default=None, alias="privateFiles")
    cc_files: Optional[StrictStr] = Field(default=None, alias="ccFiles")
    keep_folder_structure: Optional[StrictBool] = Field(default=None, alias="keepFolderStructure")
    __properties: ClassVar[List[str]] = ["folders", "privateFiles", "ccFiles", "keepFolderStructure"]

    @field_validator('folders')
    def folders_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['none', 'assign', 'delete']):
            raise ValueError("must be one of enum values ('none', 'assign', 'delete')")
        return value

    @field_validator('private_files')
    def private_files_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['none', 'assign', 'delete']):
            raise ValueError("must be one of enum values ('none', 'assign', 'delete')")
        return value

    @field_validator('cc_files')
    def cc_files_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['none', 'assign', 'delete']):
            raise ValueError("must be one of enum values ('none', 'assign', 'delete')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of HomeFolderOptions from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of HomeFolderOptions from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "folders": obj.get("folders"),
            "privateFiles": obj.get("privateFiles"),
            "ccFiles": obj.get("ccFiles"),
            "keepFolderStructure": obj.get("keepFolderStructure")
        })
        return _obj


