# coding: utf-8

"""
    edu-sharing Repository REST API

    The public restful API of the edu-sharing repository.  # noqa: E501

    OpenAPI spec version: 1.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class SimpleEdit(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'global_groups': 'list[SimpleEditGlobalGroups]',
        'organization': 'SimpleEditOrganization',
        'organization_filter': 'str'
    }

    attribute_map = {
        'global_groups': 'globalGroups',
        'organization': 'organization',
        'organization_filter': 'organizationFilter'
    }

    def __init__(self, global_groups=None, organization=None, organization_filter=None):  # noqa: E501
        """SimpleEdit - a model defined in Swagger"""  # noqa: E501
        self._global_groups = None
        self._organization = None
        self._organization_filter = None
        self.discriminator = None
        if global_groups is not None:
            self.global_groups = global_groups
        if organization is not None:
            self.organization = organization
        if organization_filter is not None:
            self.organization_filter = organization_filter

    @property
    def global_groups(self):
        """Gets the global_groups of this SimpleEdit.  # noqa: E501


        :return: The global_groups of this SimpleEdit.  # noqa: E501
        :rtype: list[SimpleEditGlobalGroups]
        """
        return self._global_groups

    @global_groups.setter
    def global_groups(self, global_groups):
        """Sets the global_groups of this SimpleEdit.


        :param global_groups: The global_groups of this SimpleEdit.  # noqa: E501
        :type: list[SimpleEditGlobalGroups]
        """

        self._global_groups = global_groups

    @property
    def organization(self):
        """Gets the organization of this SimpleEdit.  # noqa: E501


        :return: The organization of this SimpleEdit.  # noqa: E501
        :rtype: SimpleEditOrganization
        """
        return self._organization

    @organization.setter
    def organization(self, organization):
        """Sets the organization of this SimpleEdit.


        :param organization: The organization of this SimpleEdit.  # noqa: E501
        :type: SimpleEditOrganization
        """

        self._organization = organization

    @property
    def organization_filter(self):
        """Gets the organization_filter of this SimpleEdit.  # noqa: E501


        :return: The organization_filter of this SimpleEdit.  # noqa: E501
        :rtype: str
        """
        return self._organization_filter

    @organization_filter.setter
    def organization_filter(self, organization_filter):
        """Sets the organization_filter of this SimpleEdit.


        :param organization_filter: The organization_filter of this SimpleEdit.  # noqa: E501
        :type: str
        """

        self._organization_filter = organization_filter

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SimpleEdit, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SimpleEdit):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
