FROM python:3.10.13-bookworm

# ENV CRAWLER wirlernenonline_spider

RUN mkdir /opt/scrapy

WORKDIR /opt/scrapy

RUN apt-get update && \
    apt-get install -y wget && \
    apt-get install -y python3-lxml && \
    apt-get install -y libxml2-dev libxslt-dev && \
    apt-get install -y openjdk-17-jre-headless && \
    apt-get install -y npm && \
    apt-get clean;

COPY entrypoint_scrapyd.sh entrypoint_scrapyd.sh
COPY requirements.txt requirements.txt
COPY scrapy.cfg scrapy.cfg
COPY setup.cfg setup.cfg
COPY converter/ converter/
COPY csv/ csv/
COPY edu_sharing_client/ edu_sharing_client/
COPY valuespace_converter/ valuespace_converter/
RUN pip3 install -r requirements.txt

RUN echo "Install Z-API ---------------------------- "
COPY api-docs.xml api-docs.xml
COPY generate-z-api.sh generate-z-api.sh
RUN ./generate-z-api.sh

COPY generate-scrapyd.sh generate-scrapyd.sh
SHELL ["/bin/bash", "-c"]
RUN ./generate-scrapyd.sh
RUN pip3 install git+https://github.com/jdmansour/gen-crawler-ui.git@add_pyproject

# ENTRYPOINT ["/opt/scrapy/entrypoint_scrapyd.sh"]