#!/bin/bash

crawler="sodix_spider"
echo "EDU_SHARING_BASE_URL=$EDU_SHARING_BASE_URL"
echo "EDU_SHARING_USERNAME=$EDU_SHARING_USERNAME"
echo "SODIX_USER=$SODIX_USER"
echo "CRAWLER=$crawler"
docker run -e "EDU_SHARING_BASE_URL=$EDU_SHARING_BASE_URL" -e "EDU_SHARING_USERNAME=$EDU_SHARING_USERNAME" -e "EDU_SHARING_PASSWORD=$EDU_SHARING_PASSWORD" -e "SODIX_USER=$SODIX_USER" -e "SODIX_PASSWORD=$SODIX_PASSWORD" -e "CRAWLER=$crawler" oeh-search-etl
