from scrapy import Spider as Spider, signals as signals
from scrapy.core.engine import ExecutionEngine as ExecutionEngine
from scrapy.exceptions import ScrapyDeprecationWarning as ScrapyDeprecationWarning
from scrapy.extension import ExtensionManager as ExtensionManager
from scrapy.interfaces import ISpiderLoader as ISpiderLoader
from scrapy.settings import Settings as Settings, overridden_settings as overridden_settings
from scrapy.signalmanager import SignalManager as SignalManager
from scrapy.utils.log import LogCounterHandler as LogCounterHandler, configure_logging as configure_logging, get_scrapy_root_handler as get_scrapy_root_handler, install_scrapy_root_handler as install_scrapy_root_handler, log_scrapy_info as log_scrapy_info
from scrapy.utils.misc import create_instance as create_instance, load_object as load_object
from scrapy.utils.ossignal import install_shutdown_handlers as install_shutdown_handlers, signal_names as signal_names
from scrapy.utils.reactor import install_reactor as install_reactor, verify_installed_reactor as verify_installed_reactor
from typing import Any, Optional

logger: Any

class Crawler:
    spidercls: Any = ...
    settings: Any = ...
    signals: Any = ...
    stats: Any = ...
    logformatter: Any = ...
    extensions: Any = ...
    crawling: bool = ...
    spider: Any = ...
    engine: Any = ...
    def __init__(self, spidercls: Any, settings: Optional[Any] = ...): ...
    def crawl(self, *args: Any, **kwargs: Any) -> None: ...
    def stop(self) -> None: ...

class CrawlerRunner:
    crawlers: Any = ...
    settings: Any = ...
    spider_loader: Any = ...
    bootstrap_failed: bool = ...
    def __init__(self, settings: Optional[Any] = ...) -> None: ...
    @property
    def spiders(self): ...
    def crawl(self, crawler_or_spidercls: Any, *args: Any, **kwargs: Any): ...
    def create_crawler(self, crawler_or_spidercls: Any): ...
    def stop(self): ...
    def join(self) -> None: ...

class CrawlerProcess(CrawlerRunner):
    def __init__(self, settings: Optional[Any] = ..., install_root_handler: bool = ...) -> None: ...
    def start(self, stop_after_crawl: bool = ...) -> None: ...
