from scrapy.utils.job import job_dir as job_dir
from scrapy.utils.request import referer_str as referer_str, request_fingerprint as request_fingerprint
from typing import Any, Optional

class BaseDupeFilter:
    @classmethod
    def from_settings(cls, settings: Any): ...
    def request_seen(self, request: Any): ...
    def open(self) -> None: ...
    def close(self, reason: Any) -> None: ...
    def log(self, request: Any, spider: Any) -> None: ...

class RFPDupeFilter(BaseDupeFilter):
    file: Any = ...
    fingerprints: Any = ...
    logdupes: bool = ...
    debug: Any = ...
    logger: Any = ...
    def __init__(self, path: Optional[Any] = ..., debug: bool = ...) -> None: ...
    @classmethod
    def from_settings(cls, settings: Any): ...
    def request_seen(self, request: Any): ...
    def request_fingerprint(self, request: Any): ...
    def close(self, reason: Any) -> None: ...
    def log(self, request: Any, spider: Any) -> None: ...
