from typing import Any

class NotConfigured(Exception): ...
class _InvalidOutput(TypeError): ...
class IgnoreRequest(Exception): ...
class DontCloseSpider(Exception): ...

class CloseSpider(Exception):
    reason: Any = ...
    def __init__(self, reason: str = ...) -> None: ...

class StopDownload(Exception):
    fail: Any = ...
    def __init__(self, *, fail: bool = ...) -> None: ...

class DropItem(Exception): ...
class NotSupported(Exception): ...

class UsageError(Exception):
    print_help: Any = ...
    def __init__(self, *a: Any, **kw: Any) -> None: ...

class ScrapyDeprecationWarning(Warning): ...
class ContractFail(AssertionError): ...
