from scrapy.utils.request import referer_str as referer_str
from typing import Any, Optional

SCRAPEDMSG: Any
DROPPEDMSG: Any
CRAWLEDMSG: str
ITEMERRORMSG: str
SPIDERERRORMSG: str
DOWNLOADERRORMSG_SHORT: str
DOWNLOADERRORMSG_LONG: str

class LogFormatter:
    def crawled(self, request: Any, response: Any, spider: Any): ...
    def scraped(self, item: Any, response: Any, spider: Any): ...
    def dropped(self, item: Any, exception: Any, response: Any, spider: Any): ...
    def item_error(self, item: Any, exception: Any, response: Any, spider: Any): ...
    def spider_error(self, failure: Any, request: Any, response: Any, spider: Any): ...
    def download_error(self, failure: Any, request: Any, spider: Any, errmsg: Optional[Any] = ...): ...
    @classmethod
    def from_crawler(cls, crawler: Any): ...
