from scrapy.utils.misc import arg_to_iter as arg_to_iter
from scrapy.utils.python import to_bytes as to_bytes
from typing import Any, Optional

logger: Any

class MailSender:
    smtphost: Any = ...
    smtpport: Any = ...
    smtpuser: Any = ...
    smtppass: Any = ...
    smtptls: Any = ...
    smtpssl: Any = ...
    mailfrom: Any = ...
    debug: Any = ...
    def __init__(self, smtphost: str = ..., mailfrom: str = ..., smtpuser: Optional[Any] = ..., smtppass: Optional[Any] = ..., smtpport: int = ..., smtptls: bool = ..., smtpssl: bool = ..., debug: bool = ...) -> None: ...
    @classmethod
    def from_settings(cls, settings: Any): ...
    def send(self, to: Any, subject: Any, body: Any, cc: Optional[Any] = ..., attachs: Any = ..., mimetype: str = ..., charset: Optional[Any] = ..., _callback: Optional[Any] = ...): ...
