from scrapy.http import Response as Response
from scrapy.utils.misc import load_object as load_object
from scrapy.utils.python import binary_is_text as binary_is_text, to_bytes as to_bytes, to_unicode as to_unicode
from typing import Any, Optional

class ResponseTypes:
    CLASSES: Any = ...
    classes: Any = ...
    mimetypes: Any = ...
    def __init__(self) -> None: ...
    def from_mimetype(self, mimetype: Any): ...
    def from_content_type(self, content_type: Any, content_encoding: Optional[Any] = ...): ...
    def from_content_disposition(self, content_disposition: Any): ...
    def from_headers(self, headers: Any): ...
    def from_filename(self, filename: Any): ...
    def from_body(self, body: Any): ...
    def from_args(self, headers: Optional[Any] = ..., url: Optional[Any] = ..., filename: Optional[Any] = ..., body: Optional[Any] = ...): ...

responsetypes: Any
