from scrapy.crawler import Crawler as Crawler
from scrapy.exceptions import IgnoreRequest as IgnoreRequest
from scrapy.http import Request as Request, Response as Response
from scrapy.settings import Settings as Settings
from scrapy.spiders import Spider as Spider
from scrapy.utils.conf import get_config as get_config
from scrapy.utils.console import DEFAULT_PYTHON_SHELLS as DEFAULT_PYTHON_SHELLS, start_python_console as start_python_console
from scrapy.utils.datatypes import SequenceExclude as SequenceExclude
from scrapy.utils.misc import load_object as load_object
from scrapy.utils.response import open_in_browser as open_in_browser
from typing import Any, Optional

class Shell:
    relevant_classes: Any = ...
    crawler: Any = ...
    update_vars: Any = ...
    item_class: Any = ...
    spider: Any = ...
    inthread: Any = ...
    code: Any = ...
    vars: Any = ...
    def __init__(self, crawler: Any, update_vars: Optional[Any] = ..., code: Optional[Any] = ...) -> None: ...
    def start(self, url: Optional[Any] = ..., request: Optional[Any] = ..., response: Optional[Any] = ..., spider: Optional[Any] = ..., redirect: bool = ...) -> None: ...
    def fetch(self, request_or_url: Any, spider: Optional[Any] = ..., redirect: bool = ..., **kwargs: Any) -> None: ...
    def populate_vars(self, response: Optional[Any] = ..., request: Optional[Any] = ..., spider: Optional[Any] = ...) -> None: ...
    def print_help(self) -> None: ...
    def get_help(self): ...

def inspect_response(response: Any, spider: Any) -> None: ...
