from scrapy.interfaces import ISpiderLoader as ISpiderLoader
from scrapy.utils.misc import walk_modules as walk_modules
from scrapy.utils.spider import iter_spider_classes as iter_spider_classes
from typing import Any

class SpiderLoader:
    spider_modules: Any = ...
    warn_only: Any = ...
    def __init__(self, settings: Any) -> None: ...
    @classmethod
    def from_settings(cls, settings: Any): ...
    def load(self, spider_name: Any): ...
    def find_by_request(self, request: Any): ...
    def list(self): ...
