# coding: utf-8

"""
    edu-sharing Repository REST API

    The public restful API of the edu-sharing repository.  # noqa: E501

    OpenAPI spec version: 1.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class AccumulatedRatings(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'overall': 'RatingData',
        'user': 'float',
        'affiliation': 'dict(str, RatingData)'
    }

    attribute_map = {
        'overall': 'overall',
        'user': 'user',
        'affiliation': 'affiliation'
    }

    def __init__(self, overall=None, user=None, affiliation=None):  # noqa: E501
        """AccumulatedRatings - a model defined in Swagger"""  # noqa: E501
        self._overall = None
        self._user = None
        self._affiliation = None
        self.discriminator = None
        if overall is not None:
            self.overall = overall
        if user is not None:
            self.user = user
        if affiliation is not None:
            self.affiliation = affiliation

    @property
    def overall(self):
        """Gets the overall of this AccumulatedRatings.  # noqa: E501


        :return: The overall of this AccumulatedRatings.  # noqa: E501
        :rtype: RatingData
        """
        return self._overall

    @overall.setter
    def overall(self, overall):
        """Sets the overall of this AccumulatedRatings.


        :param overall: The overall of this AccumulatedRatings.  # noqa: E501
        :type: RatingData
        """

        self._overall = overall

    @property
    def user(self):
        """Gets the user of this AccumulatedRatings.  # noqa: E501


        :return: The user of this AccumulatedRatings.  # noqa: E501
        :rtype: float
        """
        return self._user

    @user.setter
    def user(self, user):
        """Sets the user of this AccumulatedRatings.


        :param user: The user of this AccumulatedRatings.  # noqa: E501
        :type: float
        """

        self._user = user

    @property
    def affiliation(self):
        """Gets the affiliation of this AccumulatedRatings.  # noqa: E501


        :return: The affiliation of this AccumulatedRatings.  # noqa: E501
        :rtype: dict(str, RatingData)
        """
        return self._affiliation

    @affiliation.setter
    def affiliation(self, affiliation):
        """Sets the affiliation of this AccumulatedRatings.


        :param affiliation: The affiliation of this AccumulatedRatings.  # noqa: E501
        :type: dict(str, RatingData)
        """

        self._affiliation = affiliation

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AccumulatedRatings, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AccumulatedRatings):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
