# coding: utf-8

"""
    edu-sharing Repository REST API

    The public restful API of the edu-sharing repository.  # noqa: E501

    OpenAPI spec version: 1.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class AuthorityEntries(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'authorities': 'list[Authority]',
        'pagination': 'Pagination'
    }

    attribute_map = {
        'authorities': 'authorities',
        'pagination': 'pagination'
    }

    def __init__(self, authorities=None, pagination=None):  # noqa: E501
        """AuthorityEntries - a model defined in Swagger"""  # noqa: E501
        self._authorities = None
        self._pagination = None
        self.discriminator = None
        self.authorities = authorities
        self.pagination = pagination

    @property
    def authorities(self):
        """Gets the authorities of this AuthorityEntries.  # noqa: E501


        :return: The authorities of this AuthorityEntries.  # noqa: E501
        :rtype: list[Authority]
        """
        return self._authorities

    @authorities.setter
    def authorities(self, authorities):
        """Sets the authorities of this AuthorityEntries.


        :param authorities: The authorities of this AuthorityEntries.  # noqa: E501
        :type: list[Authority]
        """
        if authorities is None:
            raise ValueError("Invalid value for `authorities`, must not be `None`")  # noqa: E501

        self._authorities = authorities

    @property
    def pagination(self):
        """Gets the pagination of this AuthorityEntries.  # noqa: E501


        :return: The pagination of this AuthorityEntries.  # noqa: E501
        :rtype: Pagination
        """
        return self._pagination

    @pagination.setter
    def pagination(self, pagination):
        """Sets the pagination of this AuthorityEntries.


        :param pagination: The pagination of this AuthorityEntries.  # noqa: E501
        :type: Pagination
        """
        if pagination is None:
            raise ValueError("Invalid value for `pagination`, must not be `None`")  # noqa: E501

        self._pagination = pagination

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AuthorityEntries, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AuthorityEntries):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
