# Generated by Django 5.0.6 on 2024-06-14 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawls', '0002_filterset_filterrule'),
    ]

    operations = [
        migrations.AddField(
            model_name='filterset',
            name='crawl_job',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, related_name='filter_sets', to='crawls.crawljob'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='filterrule',
            name='filter_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='crawls.filterset'),
        ),
    ]
