# Generated by Django 5.0.6 on 2024-06-16 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawls', '0003_filterset_crawl_job_alter_filterrule_filter_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='filterrule',
            name='position',
            field=models.IntegerField(default=0),
        ),
    ]
