# Generated by Django 5.0.6 on 2024-06-16 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawls', '0004_filterrule_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='filterrule',
            name='cumulative_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='crawledurl',
            name='crawl_job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crawled_urls', to='crawls.crawljob'),
        ),
    ]
