# coding: utf-8

"""
    edu-sharing Repository REST API

    The public restful API of the edu-sharing repository.

    The version of the OpenAPI document: 1.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

import warnings
from pydantic import validate_call, Field, StrictFloat, StrictStr, StrictInt
from typing import Any, Dict, List, Optional, Tuple, Union
from typing_extensions import Annotated

from pydantic import Field, StrictBool, StrictInt, StrictStr
from typing import List, Optional
from typing_extensions import Annotated
from edu_sharing_client.models.restore_results import RestoreResults
from edu_sharing_client.models.search_result import SearchResult

from edu_sharing_client.api_client import ApiClient, RequestSerialized
from edu_sharing_client.api_response import ApiResponse
from edu_sharing_client.rest import RESTResponseType


class ARCHIVEV1Api:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client


    @validate_call
    def purge(
        self,
        repository: Annotated[StrictStr, Field(description="ID of repository (or \"-home-\" for home repository)")],
        archived_node_ids: Annotated[List[StrictStr], Field(description="archived node")],
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> str:
        """Searches for archive nodes.

        Searches for archive nodes.

        :param repository: ID of repository (or \"-home-\" for home repository) (required)
        :type repository: str
        :param archived_node_ids: archived node (required)
        :type archived_node_ids: List[str]
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._purge_serialize(
            repository=repository,
            archived_node_ids=archived_node_ids,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "str",
            '400': "ErrorResponse",
            '401': "ErrorResponse",
            '403': "ErrorResponse",
            '404': "ErrorResponse",
            '500': "ErrorResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def purge_with_http_info(
        self,
        repository: Annotated[StrictStr, Field(description="ID of repository (or \"-home-\" for home repository)")],
        archived_node_ids: Annotated[List[StrictStr], Field(description="archived node")],
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[str]:
        """Searches for archive nodes.

        Searches for archive nodes.

        :param repository: ID of repository (or \"-home-\" for home repository) (required)
        :type repository: str
        :param archived_node_ids: archived node (required)
        :type archived_node_ids: List[str]
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._purge_serialize(
            repository=repository,
            archived_node_ids=archived_node_ids,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "str",
            '400': "ErrorResponse",
            '401': "ErrorResponse",
            '403': "ErrorResponse",
            '404': "ErrorResponse",
            '500': "ErrorResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def purge_without_preload_content(
        self,
        repository: Annotated[StrictStr, Field(description="ID of repository (or \"-home-\" for home repository)")],
        archived_node_ids: Annotated[List[StrictStr], Field(description="archived node")],
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Searches for archive nodes.

        Searches for archive nodes.

        :param repository: ID of repository (or \"-home-\" for home repository) (required)
        :type repository: str
        :param archived_node_ids: archived node (required)
        :type archived_node_ids: List[str]
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._purge_serialize(
            repository=repository,
            archived_node_ids=archived_node_ids,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "str",
            '400': "ErrorResponse",
            '401': "ErrorResponse",
            '403': "ErrorResponse",
            '404': "ErrorResponse",
            '500': "ErrorResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _purge_serialize(
        self,
        repository,
        archived_node_ids,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
            'archivedNodeIds': 'multi',
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[str, Union[str, bytes]] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        if repository is not None:
            _path_params['repository'] = repository
        # process the query parameters
        if archived_node_ids is not None:
            
            _query_params.append(('archivedNodeIds', archived_node_ids))
            
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
        ]

        return self.api_client.param_serialize(
            method='DELETE',
            resource_path='/archive/v1/purge/{repository}',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    def restore(
        self,
        repository: Annotated[StrictStr, Field(description="ID of repository (or \"-home-\" for home repository)")],
        archived_node_ids: Annotated[List[StrictStr], Field(description="archived nodes")],
        target: Annotated[Optional[StrictStr], Field(description="to target")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RestoreResults:
        """restore archived nodes.

        restores archived nodes. restoreStatus can have the following values: FALLBACK_PARENT_NOT_EXISTS, FALLBACK_PARENT_NO_PERMISSION, DUPLICATENAME, FINE

        :param repository: ID of repository (or \"-home-\" for home repository) (required)
        :type repository: str
        :param archived_node_ids: archived nodes (required)
        :type archived_node_ids: List[str]
        :param target: to target
        :type target: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._restore_serialize(
            repository=repository,
            archived_node_ids=archived_node_ids,
            target=target,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "RestoreResults",
            '400': "ErrorResponse",
            '401': "ErrorResponse",
            '403': "ErrorResponse",
            '404': "ErrorResponse",
            '500': "ErrorResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def restore_with_http_info(
        self,
        repository: Annotated[StrictStr, Field(description="ID of repository (or \"-home-\" for home repository)")],
        archived_node_ids: Annotated[List[StrictStr], Field(description="archived nodes")],
        target: Annotated[Optional[StrictStr], Field(description="to target")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[RestoreResults]:
        """restore archived nodes.

        restores archived nodes. restoreStatus can have the following values: FALLBACK_PARENT_NOT_EXISTS, FALLBACK_PARENT_NO_PERMISSION, DUPLICATENAME, FINE

        :param repository: ID of repository (or \"-home-\" for home repository) (required)
        :type repository: str
        :param archived_node_ids: archived nodes (required)
        :type archived_node_ids: List[str]
        :param target: to target
        :type target: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._restore_serialize(
            repository=repository,
            archived_node_ids=archived_node_ids,
            target=target,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "RestoreResults",
            '400': "ErrorResponse",
            '401': "ErrorResponse",
            '403': "ErrorResponse",
            '404': "ErrorResponse",
            '500': "ErrorResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def restore_without_preload_content(
        self,
        repository: Annotated[StrictStr, Field(description="ID of repository (or \"-home-\" for home repository)")],
        archived_node_ids: Annotated[List[StrictStr], Field(description="archived nodes")],
        target: Annotated[Optional[StrictStr], Field(description="to target")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """restore archived nodes.

        restores archived nodes. restoreStatus can have the following values: FALLBACK_PARENT_NOT_EXISTS, FALLBACK_PARENT_NO_PERMISSION, DUPLICATENAME, FINE

        :param repository: ID of repository (or \"-home-\" for home repository) (required)
        :type repository: str
        :param archived_node_ids: archived nodes (required)
        :type archived_node_ids: List[str]
        :param target: to target
        :type target: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._restore_serialize(
            repository=repository,
            archived_node_ids=archived_node_ids,
            target=target,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "RestoreResults",
            '400': "ErrorResponse",
            '401': "ErrorResponse",
            '403': "ErrorResponse",
            '404': "ErrorResponse",
            '500': "ErrorResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _restore_serialize(
        self,
        repository,
        archived_node_ids,
        target,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
            'archivedNodeIds': 'multi',
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[str, Union[str, bytes]] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        if repository is not None:
            _path_params['repository'] = repository
        # process the query parameters
        if archived_node_ids is not None:
            
            _query_params.append(('archivedNodeIds', archived_node_ids))
            
        if target is not None:
            
            _query_params.append(('target', target))
            
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
        ]

        return self.api_client.param_serialize(
            method='POST',
            resource_path='/archive/v1/restore/{repository}',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    def search_archive(
        self,
        repository: Annotated[StrictStr, Field(description="ID of repository (or \"-home-\" for home repository)")],
        pattern: Annotated[StrictStr, Field(description="search pattern")],
        max_items: Annotated[Optional[StrictInt], Field(description="maximum items per page")] = None,
        skip_count: Annotated[Optional[StrictInt], Field(description="skip a number of items")] = None,
        sort_properties: Annotated[Optional[List[StrictStr]], Field(description="sort properties")] = None,
        sort_ascending: Annotated[Optional[List[StrictBool]], Field(description="sort ascending")] = None,
        property_filter: Annotated[Optional[List[StrictStr]], Field(description="property filter for result nodes (or \"-all-\" for all properties)")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> SearchResult:
        """Searches for archive nodes.

        Searches for archive nodes.

        :param repository: ID of repository (or \"-home-\" for home repository) (required)
        :type repository: str
        :param pattern: search pattern (required)
        :type pattern: str
        :param max_items: maximum items per page
        :type max_items: int
        :param skip_count: skip a number of items
        :type skip_count: int
        :param sort_properties: sort properties
        :type sort_properties: List[str]
        :param sort_ascending: sort ascending
        :type sort_ascending: List[bool]
        :param property_filter: property filter for result nodes (or \"-all-\" for all properties)
        :type property_filter: List[str]
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._search_archive_serialize(
            repository=repository,
            pattern=pattern,
            max_items=max_items,
            skip_count=skip_count,
            sort_properties=sort_properties,
            sort_ascending=sort_ascending,
            property_filter=property_filter,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "SearchResult",
            '400': "ErrorResponse",
            '401': "ErrorResponse",
            '403': "ErrorResponse",
            '404': "ErrorResponse",
            '500': "ErrorResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def search_archive_with_http_info(
        self,
        repository: Annotated[StrictStr, Field(description="ID of repository (or \"-home-\" for home repository)")],
        pattern: Annotated[StrictStr, Field(description="search pattern")],
        max_items: Annotated[Optional[StrictInt], Field(description="maximum items per page")] = None,
        skip_count: Annotated[Optional[StrictInt], Field(description="skip a number of items")] = None,
        sort_properties: Annotated[Optional[List[StrictStr]], Field(description="sort properties")] = None,
        sort_ascending: Annotated[Optional[List[StrictBool]], Field(description="sort ascending")] = None,
        property_filter: Annotated[Optional[List[StrictStr]], Field(description="property filter for result nodes (or \"-all-\" for all properties)")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[SearchResult]:
        """Searches for archive nodes.

        Searches for archive nodes.

        :param repository: ID of repository (or \"-home-\" for home repository) (required)
        :type repository: str
        :param pattern: search pattern (required)
        :type pattern: str
        :param max_items: maximum items per page
        :type max_items: int
        :param skip_count: skip a number of items
        :type skip_count: int
        :param sort_properties: sort properties
        :type sort_properties: List[str]
        :param sort_ascending: sort ascending
        :type sort_ascending: List[bool]
        :param property_filter: property filter for result nodes (or \"-all-\" for all properties)
        :type property_filter: List[str]
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._search_archive_serialize(
            repository=repository,
            pattern=pattern,
            max_items=max_items,
            skip_count=skip_count,
            sort_properties=sort_properties,
            sort_ascending=sort_ascending,
            property_filter=property_filter,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "SearchResult",
            '400': "ErrorResponse",
            '401': "ErrorResponse",
            '403': "ErrorResponse",
            '404': "ErrorResponse",
            '500': "ErrorResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def search_archive_without_preload_content(
        self,
        repository: Annotated[StrictStr, Field(description="ID of repository (or \"-home-\" for home repository)")],
        pattern: Annotated[StrictStr, Field(description="search pattern")],
        max_items: Annotated[Optional[StrictInt], Field(description="maximum items per page")] = None,
        skip_count: Annotated[Optional[StrictInt], Field(description="skip a number of items")] = None,
        sort_properties: Annotated[Optional[List[StrictStr]], Field(description="sort properties")] = None,
        sort_ascending: Annotated[Optional[List[StrictBool]], Field(description="sort ascending")] = None,
        property_filter: Annotated[Optional[List[StrictStr]], Field(description="property filter for result nodes (or \"-all-\" for all properties)")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Searches for archive nodes.

        Searches for archive nodes.

        :param repository: ID of repository (or \"-home-\" for home repository) (required)
        :type repository: str
        :param pattern: search pattern (required)
        :type pattern: str
        :param max_items: maximum items per page
        :type max_items: int
        :param skip_count: skip a number of items
        :type skip_count: int
        :param sort_properties: sort properties
        :type sort_properties: List[str]
        :param sort_ascending: sort ascending
        :type sort_ascending: List[bool]
        :param property_filter: property filter for result nodes (or \"-all-\" for all properties)
        :type property_filter: List[str]
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._search_archive_serialize(
            repository=repository,
            pattern=pattern,
            max_items=max_items,
            skip_count=skip_count,
            sort_properties=sort_properties,
            sort_ascending=sort_ascending,
            property_filter=property_filter,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "SearchResult",
            '400': "ErrorResponse",
            '401': "ErrorResponse",
            '403': "ErrorResponse",
            '404': "ErrorResponse",
            '500': "ErrorResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _search_archive_serialize(
        self,
        repository,
        pattern,
        max_items,
        skip_count,
        sort_properties,
        sort_ascending,
        property_filter,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
            'sortProperties': 'multi',
            'sortAscending': 'multi',
            'propertyFilter': 'multi',
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[str, Union[str, bytes]] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        if repository is not None:
            _path_params['repository'] = repository
        if pattern is not None:
            _path_params['pattern'] = pattern
        # process the query parameters
        if max_items is not None:
            
            _query_params.append(('maxItems', max_items))
            
        if skip_count is not None:
            
            _query_params.append(('skipCount', skip_count))
            
        if sort_properties is not None:
            
            _query_params.append(('sortProperties', sort_properties))
            
        if sort_ascending is not None:
            
            _query_params.append(('sortAscending', sort_ascending))
            
        if property_filter is not None:
            
            _query_params.append(('propertyFilter', property_filter))
            
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/archive/v1/search/{repository}/{pattern}',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    def search_archive_person(
        self,
        repository: Annotated[StrictStr, Field(description="ID of repository (or \"-home-\" for home repository)")],
        pattern: Annotated[StrictStr, Field(description="search pattern")],
        person: Annotated[StrictStr, Field(description="person")],
        max_items: Annotated[Optional[StrictInt], Field(description="maximum items per page")] = None,
        skip_count: Annotated[Optional[StrictInt], Field(description="skip a number of items")] = None,
        sort_properties: Annotated[Optional[List[StrictStr]], Field(description="sort properties")] = None,
        sort_ascending: Annotated[Optional[List[StrictBool]], Field(description="sort ascending")] = None,
        property_filter: Annotated[Optional[List[StrictStr]], Field(description="property filter for result nodes (or \"-all-\" for all properties)")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> SearchResult:
        """Searches for archive nodes.

        Searches for archive nodes.

        :param repository: ID of repository (or \"-home-\" for home repository) (required)
        :type repository: str
        :param pattern: search pattern (required)
        :type pattern: str
        :param person: person (required)
        :type person: str
        :param max_items: maximum items per page
        :type max_items: int
        :param skip_count: skip a number of items
        :type skip_count: int
        :param sort_properties: sort properties
        :type sort_properties: List[str]
        :param sort_ascending: sort ascending
        :type sort_ascending: List[bool]
        :param property_filter: property filter for result nodes (or \"-all-\" for all properties)
        :type property_filter: List[str]
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._search_archive_person_serialize(
            repository=repository,
            pattern=pattern,
            person=person,
            max_items=max_items,
            skip_count=skip_count,
            sort_properties=sort_properties,
            sort_ascending=sort_ascending,
            property_filter=property_filter,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "SearchResult",
            '400': "ErrorResponse",
            '401': "ErrorResponse",
            '403': "ErrorResponse",
            '404': "ErrorResponse",
            '500': "ErrorResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def search_archive_person_with_http_info(
        self,
        repository: Annotated[StrictStr, Field(description="ID of repository (or \"-home-\" for home repository)")],
        pattern: Annotated[StrictStr, Field(description="search pattern")],
        person: Annotated[StrictStr, Field(description="person")],
        max_items: Annotated[Optional[StrictInt], Field(description="maximum items per page")] = None,
        skip_count: Annotated[Optional[StrictInt], Field(description="skip a number of items")] = None,
        sort_properties: Annotated[Optional[List[StrictStr]], Field(description="sort properties")] = None,
        sort_ascending: Annotated[Optional[List[StrictBool]], Field(description="sort ascending")] = None,
        property_filter: Annotated[Optional[List[StrictStr]], Field(description="property filter for result nodes (or \"-all-\" for all properties)")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[SearchResult]:
        """Searches for archive nodes.

        Searches for archive nodes.

        :param repository: ID of repository (or \"-home-\" for home repository) (required)
        :type repository: str
        :param pattern: search pattern (required)
        :type pattern: str
        :param person: person (required)
        :type person: str
        :param max_items: maximum items per page
        :type max_items: int
        :param skip_count: skip a number of items
        :type skip_count: int
        :param sort_properties: sort properties
        :type sort_properties: List[str]
        :param sort_ascending: sort ascending
        :type sort_ascending: List[bool]
        :param property_filter: property filter for result nodes (or \"-all-\" for all properties)
        :type property_filter: List[str]
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._search_archive_person_serialize(
            repository=repository,
            pattern=pattern,
            person=person,
            max_items=max_items,
            skip_count=skip_count,
            sort_properties=sort_properties,
            sort_ascending=sort_ascending,
            property_filter=property_filter,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "SearchResult",
            '400': "ErrorResponse",
            '401': "ErrorResponse",
            '403': "ErrorResponse",
            '404': "ErrorResponse",
            '500': "ErrorResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def search_archive_person_without_preload_content(
        self,
        repository: Annotated[StrictStr, Field(description="ID of repository (or \"-home-\" for home repository)")],
        pattern: Annotated[StrictStr, Field(description="search pattern")],
        person: Annotated[StrictStr, Field(description="person")],
        max_items: Annotated[Optional[StrictInt], Field(description="maximum items per page")] = None,
        skip_count: Annotated[Optional[StrictInt], Field(description="skip a number of items")] = None,
        sort_properties: Annotated[Optional[List[StrictStr]], Field(description="sort properties")] = None,
        sort_ascending: Annotated[Optional[List[StrictBool]], Field(description="sort ascending")] = None,
        property_filter: Annotated[Optional[List[StrictStr]], Field(description="property filter for result nodes (or \"-all-\" for all properties)")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Searches for archive nodes.

        Searches for archive nodes.

        :param repository: ID of repository (or \"-home-\" for home repository) (required)
        :type repository: str
        :param pattern: search pattern (required)
        :type pattern: str
        :param person: person (required)
        :type person: str
        :param max_items: maximum items per page
        :type max_items: int
        :param skip_count: skip a number of items
        :type skip_count: int
        :param sort_properties: sort properties
        :type sort_properties: List[str]
        :param sort_ascending: sort ascending
        :type sort_ascending: List[bool]
        :param property_filter: property filter for result nodes (or \"-all-\" for all properties)
        :type property_filter: List[str]
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._search_archive_person_serialize(
            repository=repository,
            pattern=pattern,
            person=person,
            max_items=max_items,
            skip_count=skip_count,
            sort_properties=sort_properties,
            sort_ascending=sort_ascending,
            property_filter=property_filter,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "SearchResult",
            '400': "ErrorResponse",
            '401': "ErrorResponse",
            '403': "ErrorResponse",
            '404': "ErrorResponse",
            '500': "ErrorResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _search_archive_person_serialize(
        self,
        repository,
        pattern,
        person,
        max_items,
        skip_count,
        sort_properties,
        sort_ascending,
        property_filter,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
            'sortProperties': 'multi',
            'sortAscending': 'multi',
            'propertyFilter': 'multi',
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[str, Union[str, bytes]] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        if repository is not None:
            _path_params['repository'] = repository
        if pattern is not None:
            _path_params['pattern'] = pattern
        if person is not None:
            _path_params['person'] = person
        # process the query parameters
        if max_items is not None:
            
            _query_params.append(('maxItems', max_items))
            
        if skip_count is not None:
            
            _query_params.append(('skipCount', skip_count))
            
        if sort_properties is not None:
            
            _query_params.append(('sortProperties', sort_properties))
            
        if sort_ascending is not None:
            
            _query_params.append(('sortAscending', sort_ascending))
            
        if property_filter is not None:
            
            _query_params.append(('propertyFilter', property_filter))
            
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/archive/v1/search/{repository}/{pattern}/{person}',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )


