from scrapy.utils.misc import create_instance as create_instance, load_object as load_object
from scrapy.utils.python import to_unicode as to_unicode
from typing import Any, Optional

class HTTP10DownloadHandler:
    lazy: bool = ...
    HTTPClientFactory: Any = ...
    ClientContextFactory: Any = ...
    def __init__(self, settings: Any, crawler: Optional[Any] = ...) -> None: ...
    @classmethod
    def from_crawler(cls, crawler: Any): ...
    def download_request(self, request: Any, spider: Any): ...
