from scrapy.core.downloader.handlers.http import HTTPDownloadHandler as HTTPDownloadHandler
from scrapy.exceptions import NotConfigured as NotConfigured
from scrapy.utils.boto import is_botocore_available as is_botocore_available
from scrapy.utils.httpobj import urlparse_cached as urlparse_cached
from scrapy.utils.misc import create_instance as create_instance
from typing import Any, Optional

class S3DownloadHandler:
    anon: Any = ...
    def __init__(self, settings: Any, *, crawler: Optional[Any] = ..., aws_access_key_id: Optional[Any] = ..., aws_secret_access_key: Optional[Any] = ..., httpdownloadhandler: Any = ..., **kw: Any) -> None: ...
    @classmethod
    def from_crawler(cls, crawler: Any, **kwargs: Any): ...
    def download_request(self, request: Any, spider: Any): ...
