from scrapy import signals as signals
from scrapy.exceptions import NotConfigured as NotConfigured
from scrapy.utils.trackref import live_refs as live_refs
from typing import Any

class MemoryDebugger:
    stats: Any = ...
    def __init__(self, stats: Any) -> None: ...
    @classmethod
    def from_crawler(cls, crawler: Any): ...
    def spider_closed(self, spider: Any, reason: Any) -> None: ...
