from scrapy import signals as signals
from scrapy.exceptions import NotConfigured as NotConfigured
from scrapy.mail import MailSender as MailSender
from scrapy.utils.engine import get_engine_status as get_engine_status
from typing import Any

logger: Any

class MemoryUsage:
    resource: Any = ...
    crawler: Any = ...
    warned: bool = ...
    notify_mails: Any = ...
    limit: Any = ...
    warning: Any = ...
    check_interval: Any = ...
    mail: Any = ...
    def __init__(self, crawler: Any) -> None: ...
    @classmethod
    def from_crawler(cls, crawler: Any): ...
    def get_virtual_size(self): ...
    tasks: Any = ...
    def engine_started(self) -> None: ...
    def engine_stopped(self) -> None: ...
    def update(self) -> None: ...
