from scrapy import signals as signals
from scrapy.exceptions import NotConfigured as NotConfigured
from scrapy.utils.job import job_dir as job_dir
from typing import Any, Optional

class SpiderState:
    jobdir: Any = ...
    def __init__(self, jobdir: Optional[Any] = ...) -> None: ...
    @classmethod
    def from_crawler(cls, crawler: Any): ...
    def spider_closed(self, spider: Any) -> None: ...
    def spider_opened(self, spider: Any) -> None: ...
    @property
    def statefn(self): ...
