from scrapy import signals as signals
from scrapy.exceptions import NotConfigured as NotConfigured
from scrapy.mail import MailSender as MailSender
from typing import Any

class StatsMailer:
    stats: Any = ...
    recipients: Any = ...
    mail: Any = ...
    def __init__(self, stats: Any, recipients: Any, mail: Any) -> None: ...
    @classmethod
    def from_crawler(cls, crawler: Any): ...
    def spider_closed(self, spider: Any): ...
