from scrapy import signals as signals
from scrapy.exceptions import NotConfigured as NotConfigured
from typing import Any

logger: Any

class AutoThrottle:
    crawler: Any = ...
    debug: Any = ...
    target_concurrency: Any = ...
    def __init__(self, crawler: Any) -> None: ...
    @classmethod
    def from_crawler(cls, crawler: Any): ...
