from scrapy.exceptions import NotConfigured as NotConfigured
from scrapy.http import HtmlResponse as HtmlResponse
from typing import Any

logger: Any

class AjaxCrawlMiddleware:
    lookup_bytes: Any = ...
    def __init__(self, settings: Any) -> None: ...
    @classmethod
    def from_crawler(cls, crawler: Any): ...
    def process_response(self, request: Any, response: Any, spider: Any): ...
