from scrapy.exceptions import NotConfigured as NotConfigured
from scrapy.http import Response as Response
from scrapy.http.cookies import CookieJar as CookieJar
from scrapy.utils.python import to_unicode as to_unicode
from typing import Any

logger: Any

class CookiesMiddleware:
    jars: Any = ...
    debug: Any = ...
    def __init__(self, debug: bool = ...) -> None: ...
    @classmethod
    def from_crawler(cls, crawler: Any): ...
    def process_request(self, request: Any, spider: Any) -> None: ...
    def process_response(self, request: Any, response: Any, spider: Any): ...
