from scrapy.utils.python import without_none_values as without_none_values
from typing import Any

class DefaultHeadersMiddleware:
    def __init__(self, headers: Any) -> None: ...
    @classmethod
    def from_crawler(cls, crawler: Any): ...
    def process_request(self, request: Any, spider: Any) -> None: ...
