from scrapy import signals as signals
from typing import Any

class DownloadTimeoutMiddleware:
    def __init__(self, timeout: int = ...) -> None: ...
    @classmethod
    def from_crawler(cls, crawler: Any): ...
    def spider_opened(self, spider: Any) -> None: ...
    def process_request(self, request: Any, spider: Any) -> None: ...
