from scrapy import signals as signals
from typing import Any

class HttpAuthMiddleware:
    @classmethod
    def from_crawler(cls, crawler: Any): ...
    auth: Any = ...
    def spider_opened(self, spider: Any) -> None: ...
    def process_request(self, request: Any, spider: Any) -> None: ...
