from scrapy.exceptions import NotConfigured as NotConfigured
from scrapy.utils.httpobj import urlparse_cached as urlparse_cached
from scrapy.utils.python import to_bytes as to_bytes
from typing import Any

class HttpProxyMiddleware:
    auth_encoding: Any = ...
    proxies: Any = ...
    def __init__(self, auth_encoding: str = ...) -> None: ...
    @classmethod
    def from_crawler(cls, crawler: Any): ...
    def process_request(self, request: Any, spider: Any) -> None: ...
