from scrapy.core.downloader.handlers.http11 import TunnelError as TunnelError
from scrapy.exceptions import NotConfigured as NotConfigured
from scrapy.utils.python import global_object_name as global_object_name
from scrapy.utils.response import response_status_message as response_status_message
from typing import Any

logger: Any

class RetryMiddleware:
    EXCEPTIONS_TO_RETRY: Any = ...
    max_retry_times: Any = ...
    retry_http_codes: Any = ...
    priority_adjust: Any = ...
    def __init__(self, settings: Any) -> None: ...
    @classmethod
    def from_crawler(cls, crawler: Any): ...
    def process_response(self, request: Any, response: Any, spider: Any): ...
    def process_exception(self, request: Any, exception: Any, spider: Any): ...
