from scrapy.exceptions import IgnoreRequest as IgnoreRequest, NotConfigured as NotConfigured
from scrapy.http import Request as Request
from scrapy.utils.httpobj import urlparse_cached as urlparse_cached
from scrapy.utils.log import failure_to_exc_info as failure_to_exc_info
from scrapy.utils.misc import load_object as load_object
from typing import Any

logger: Any

class RobotsTxtMiddleware:
    DOWNLOAD_PRIORITY: int = ...
    crawler: Any = ...
    def __init__(self, crawler: Any) -> None: ...
    @classmethod
    def from_crawler(cls, crawler: Any): ...
    def process_request(self, request: Any, spider: Any): ...
    def process_request_2(self, rp: Any, request: Any, spider: Any) -> None: ...
    def robot_parser(self, request: Any, spider: Any): ...
