from scrapy.exceptions import NotConfigured as NotConfigured
from scrapy.utils.python import global_object_name as global_object_name
from scrapy.utils.request import request_httprepr as request_httprepr
from scrapy.utils.response import response_httprepr as response_httprepr
from typing import Any

class DownloaderStats:
    stats: Any = ...
    def __init__(self, stats: Any) -> None: ...
    @classmethod
    def from_crawler(cls, crawler: Any): ...
    def process_request(self, request: Any, spider: Any) -> None: ...
    def process_response(self, request: Any, response: Any, spider: Any): ...
    def process_exception(self, request: Any, exception: Any, spider: Any) -> None: ...
