from scrapy import signals as signals
from typing import Any

class UserAgentMiddleware:
    user_agent: Any = ...
    def __init__(self, user_agent: str = ...) -> None: ...
    @classmethod
    def from_crawler(cls, crawler: Any): ...
    def spider_opened(self, spider: Any) -> None: ...
    def process_request(self, request: Any, spider: Any) -> None: ...
