from scrapy.exceptions import NotConfigured as NotConfigured, NotSupported as NotSupported
from scrapy.selector import Selector as Selector
from scrapy.spiders import Spider as Spider
from scrapy.utils.iterators import csviter as csviter, xmliter as xmliter
from scrapy.utils.spider import iterate_spider_output as iterate_spider_output
from typing import Any

class XMLFeedSpider(Spider):
    iterator: str = ...
    itertag: str = ...
    namespaces: Any = ...
    def process_results(self, response: Any, results: Any): ...
    def adapt_response(self, response: Any): ...
    def parse_node(self, response: Any, selector: Any): ...
    def parse_nodes(self, response: Any, nodes: Any) -> None: ...

class CSVFeedSpider(Spider):
    delimiter: Any = ...
    quotechar: Any = ...
    headers: Any = ...
    def process_results(self, response: Any, results: Any): ...
    def adapt_response(self, response: Any): ...
    def parse_row(self, response: Any, row: Any) -> None: ...
    def parse_rows(self, response: Any) -> None: ...
