from scrapy.spiders import Spider as Spider
from scrapy.utils.spider import iterate_spider_output as iterate_spider_output
from typing import Any, Optional

class InitSpider(Spider):
    def start_requests(self): ...
    def initialized(self, response: Optional[Any] = ...): ...
    def init_request(self): ...
