from scrapy.http import Request as Request, XmlResponse as XmlResponse
from scrapy.spiders import Spider as Spider
from scrapy.utils.gz import gunzip as gunzip, gzip_magic_number as gzip_magic_number
from scrapy.utils.sitemap import Sitemap as Sitemap, sitemap_urls_from_robots as sitemap_urls_from_robots
from typing import Any

logger: Any

class SitemapSpider(Spider):
    sitemap_urls: Any = ...
    sitemap_rules: Any = ...
    sitemap_follow: Any = ...
    sitemap_alternate_links: bool = ...
    def __init__(self, *a: Any, **kw: Any) -> None: ...
    def start_requests(self) -> None: ...
    def sitemap_filter(self, entries: Any) -> None: ...

def regex(x: Any): ...
def iterloc(it: Any, alt: bool = ...) -> None: ...
