from typing import Any, Optional

class About:
    swagger_types: Any = ...
    attribute_map: Any = ...
    discriminator: Any = ...
    def __init__(self, themes_url: Optional[Any] = ..., last_cache_update: Optional[Any] = ..., version: Optional[Any] = ..., services: Optional[Any] = ...) -> None: ...
    @property
    def themes_url(self): ...
    @themes_url.setter
    def themes_url(self, themes_url: Any) -> None: ...
    @property
    def last_cache_update(self): ...
    @last_cache_update.setter
    def last_cache_update(self, last_cache_update: Any) -> None: ...
    @property
    def version(self): ...
    @version.setter
    def version(self, version: Any) -> None: ...
    @property
    def services(self): ...
    @services.setter
    def services(self, services: Any) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other: Any) -> Any: ...
    def __ne__(self, other: Any) -> Any: ...
