from typing import Any, Optional

class ACL:
    swagger_types: Any = ...
    attribute_map: Any = ...
    discriminator: Any = ...
    def __init__(self, inherited: bool = ..., permissions: Optional[Any] = ...) -> None: ...
    @property
    def inherited(self): ...
    @inherited.setter
    def inherited(self, inherited: Any) -> None: ...
    @property
    def permissions(self): ...
    @permissions.setter
    def permissions(self, permissions: Any) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other: Any) -> Any: ...
    def __ne__(self, other: Any) -> Any: ...
