from typing import Any, Optional

class Admin:
    swagger_types: Any = ...
    attribute_map: Any = ...
    discriminator: Any = ...
    def __init__(self, statistics: Optional[Any] = ...) -> None: ...
    @property
    def statistics(self): ...
    @statistics.setter
    def statistics(self, statistics: Any) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other: Any) -> Any: ...
    def __ne__(self, other: Any) -> Any: ...
