from typing import Any, Optional

class AuthorityEntries:
    swagger_types: Any = ...
    attribute_map: Any = ...
    discriminator: Any = ...
    def __init__(self, authorities: Optional[Any] = ..., pagination: Optional[Any] = ...) -> None: ...
    @property
    def authorities(self): ...
    @authorities.setter
    def authorities(self, authorities: Any) -> None: ...
    @property
    def pagination(self): ...
    @pagination.setter
    def pagination(self, pagination: Any) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other: Any) -> Any: ...
    def __ne__(self, other: Any) -> Any: ...
