from typing import Any, Optional

class Authority:
    swagger_types: Any = ...
    attribute_map: Any = ...
    discriminator: Any = ...
    def __init__(self, authority_name: Optional[Any] = ..., authority_type: Optional[Any] = ...) -> None: ...
    @property
    def authority_name(self): ...
    @authority_name.setter
    def authority_name(self, authority_name: Any) -> None: ...
    @property
    def authority_type(self): ...
    @authority_type.setter
    def authority_type(self, authority_type: Any) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other: Any) -> Any: ...
    def __ne__(self, other: Any) -> Any: ...
