from typing import Any, Optional

class Body4:
    swagger_types: Any = ...
    attribute_map: Any = ...
    discriminator: Any = ...
    def __init__(self, file: Optional[Any] = ...) -> None: ...
    @property
    def file(self): ...
    @file.setter
    def file(self, file: Any) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other: Any) -> Any: ...
    def __ne__(self, other: Any) -> Any: ...
