from typing import Any, Optional

class Body6:
    swagger_types: Any = ...
    attribute_map: Any = ...
    discriminator: Any = ...
    def __init__(self, avatar: Optional[Any] = ...) -> None: ...
    @property
    def avatar(self): ...
    @avatar.setter
    def avatar(self, avatar: Any) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other: Any) -> Any: ...
    def __ne__(self, other: Any) -> Any: ...
