from typing import Any, Optional

class Body7:
    swagger_types: Any = ...
    attribute_map: Any = ...
    discriminator: Any = ...
    def __init__(self, mc_orgs: Optional[Any] = ...) -> None: ...
    @property
    def mc_orgs(self): ...
    @mc_orgs.setter
    def mc_orgs(self, mc_orgs: Any) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other: Any) -> Any: ...
    def __ne__(self, other: Any) -> Any: ...
