from typing import Any, Optional

class Body9:
    swagger_types: Any = ...
    attribute_map: Any = ...
    discriminator: Any = ...
    def __init__(self, organisations: Optional[Any] = ...) -> None: ...
    @property
    def organisations(self): ...
    @organisations.setter
    def organisations(self, organisations: Any) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other: Any) -> Any: ...
    def __ne__(self, other: Any) -> Any: ...
