from typing import Any, Optional

class Body2:
    swagger_types: Any = ...
    attribute_map: Any = ...
    discriminator: Any = ...
    def __init__(self, excel: Optional[Any] = ...) -> None: ...
    @property
    def excel(self): ...
    @excel.setter
    def excel(self, excel: Any) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other: Any) -> Any: ...
    def __ne__(self, other: Any) -> Any: ...
