from typing import Any, Optional

class Body11:
    swagger_types: Any = ...
    attribute_map: Any = ...
    discriminator: Any = ...
    def __init__(self, image: Optional[Any] = ...) -> None: ...
    @property
    def image(self): ...
    @image.setter
    def image(self, image: Any) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other: Any) -> Any: ...
    def __ne__(self, other: Any) -> Any: ...
