from typing import Any, Optional

class Collections:
    swagger_types: Any = ...
    attribute_map: Any = ...
    discriminator: Any = ...
    def __init__(self, colors: Optional[Any] = ...) -> None: ...
    @property
    def colors(self): ...
    @colors.setter
    def colors(self, colors: Any) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other: Any) -> Any: ...
    def __ne__(self, other: Any) -> Any: ...
