from typing import Any, Optional

class CollectionCounts:
    swagger_types: Any = ...
    attribute_map: Any = ...
    discriminator: Any = ...
    def __init__(self, refs: Optional[Any] = ..., collections: Optional[Any] = ...) -> None: ...
    @property
    def refs(self): ...
    @refs.setter
    def refs(self, refs: Any) -> None: ...
    @property
    def collections(self): ...
    @collections.setter
    def collections(self, collections: Any) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other: Any) -> Any: ...
    def __ne__(self, other: Any) -> Any: ...
