from typing import Any, Optional

class ColumnV2:
    swagger_types: Any = ...
    attribute_map: Any = ...
    discriminator: Any = ...
    def __init__(self, id: Optional[Any] = ..., format: Optional[Any] = ..., show_default: bool = ...) -> None: ...
    @property
    def id(self): ...
    @id.setter
    def id(self, id: Any) -> None: ...
    @property
    def format(self): ...
    @format.setter
    def format(self, format: Any) -> None: ...
    @property
    def show_default(self): ...
    @show_default.setter
    def show_default(self, show_default: Any) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other: Any) -> Any: ...
    def __ne__(self, other: Any) -> Any: ...
