from typing import Any, Optional

class Comments:
    swagger_types: Any = ...
    attribute_map: Any = ...
    discriminator: Any = ...
    def __init__(self, comments: Optional[Any] = ...) -> None: ...
    @property
    def comments(self): ...
    @comments.setter
    def comments(self, comments: Any) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other: Any) -> Any: ...
    def __ne__(self, other: Any) -> Any: ...
