from typing import Any, Optional

class Counts:
    swagger_types: Any = ...
    attribute_map: Any = ...
    discriminator: Any = ...
    def __init__(self, elements: Optional[Any] = ...) -> None: ...
    @property
    def elements(self): ...
    @elements.setter
    def elements(self, elements: Any) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other: Any) -> Any: ...
    def __ne__(self, other: Any) -> Any: ...
