from typing import Any, Optional

class Facette:
    swagger_types: Any = ...
    attribute_map: Any = ...
    discriminator: Any = ...
    def __init__(self, _property: Optional[Any] = ..., values: Optional[Any] = ...) -> None: ...
    @property
    def values(self): ...
    @values.setter
    def values(self, values: Any) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other: Any) -> Any: ...
    def __ne__(self, other: Any) -> Any: ...
