from typing import Any, Optional

class Filter:
    swagger_types: Any = ...
    attribute_map: Any = ...
    discriminator: Any = ...
    def __init__(self, entries: Optional[Any] = ...) -> None: ...
    @property
    def entries(self): ...
    @entries.setter
    def entries(self, entries: Any) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other: Any) -> Any: ...
    def __ne__(self, other: Any) -> Any: ...
