from typing import Any, Optional

class Geo:
    swagger_types: Any = ...
    attribute_map: Any = ...
    discriminator: Any = ...
    def __init__(self, longitude: Optional[Any] = ..., latitude: Optional[Any] = ..., address_country: Optional[Any] = ...) -> None: ...
    @property
    def longitude(self): ...
    @longitude.setter
    def longitude(self, longitude: Any) -> None: ...
    @property
    def latitude(self): ...
    @latitude.setter
    def latitude(self, latitude: Any) -> None: ...
    @property
    def address_country(self): ...
    @address_country.setter
    def address_country(self, address_country: Any) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other: Any) -> Any: ...
    def __ne__(self, other: Any) -> Any: ...
