from typing import Any, Optional

class Image:
    swagger_types: Any = ...
    attribute_map: Any = ...
    discriminator: Any = ...
    def __init__(self, src: Optional[Any] = ..., replace: Optional[Any] = ...) -> None: ...
    @property
    def src(self): ...
    @src.setter
    def src(self, src: Any) -> None: ...
    @property
    def replace(self): ...
    @replace.setter
    def replace(self, replace: Any) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other: Any) -> Any: ...
    def __ne__(self, other: Any) -> Any: ...
