from typing import Any, Optional

class Language:
    swagger_types: Any = ...
    attribute_map: Any = ...
    discriminator: Any = ...
    def __init__(self, language: Optional[Any] = ..., string: Optional[Any] = ...) -> None: ...
    @property
    def language(self): ...
    @language.setter
    def language(self, language: Any) -> None: ...
    @property
    def string(self): ...
    @string.setter
    def string(self, string: Any) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other: Any) -> Any: ...
    def __ne__(self, other: Any) -> Any: ...
