from typing import Any, Optional

class Level:
    swagger_types: Any = ...
    attribute_map: Any = ...
    discriminator: Any = ...
    def __init__(self, syslog_equivalent: Optional[Any] = ...) -> None: ...
    @property
    def syslog_equivalent(self): ...
    @syslog_equivalent.setter
    def syslog_equivalent(self, syslog_equivalent: Any) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other: Any) -> Any: ...
    def __ne__(self, other: Any) -> Any: ...
