from typing import Any, Optional

class LogEntry:
    swagger_types: Any = ...
    attribute_map: Any = ...
    discriminator: Any = ...
    def __init__(self, class_name: Optional[Any] = ..., level: Optional[Any] = ..., _date: Optional[Any] = ..., message: Optional[Any] = ...) -> None: ...
    @property
    def class_name(self): ...
    @class_name.setter
    def class_name(self, class_name: Any) -> None: ...
    @property
    def level(self): ...
    @level.setter
    def level(self, level: Any) -> None: ...
    @property
    def message(self): ...
    @message.setter
    def message(self, message: Any) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other: Any) -> Any: ...
    def __ne__(self, other: Any) -> Any: ...
