from typing import Any, Optional

class LoginCredentials:
    swagger_types: Any = ...
    attribute_map: Any = ...
    discriminator: Any = ...
    def __init__(self, user_name: Optional[Any] = ..., password: Optional[Any] = ..., scope: Optional[Any] = ...) -> None: ...
    @property
    def user_name(self): ...
    @user_name.setter
    def user_name(self, user_name: Any) -> None: ...
    @property
    def password(self): ...
    @password.setter
    def password(self, password: Any) -> None: ...
    @property
    def scope(self): ...
    @scope.setter
    def scope(self, scope: Any) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other: Any) -> Any: ...
    def __ne__(self, other: Any) -> Any: ...
