from typing import Any, Optional

class LogoutInfo:
    swagger_types: Any = ...
    attribute_map: Any = ...
    discriminator: Any = ...
    def __init__(self, url: Optional[Any] = ..., destroy_session: bool = ..., ajax: bool = ..., next: Optional[Any] = ...) -> None: ...
    @property
    def url(self): ...
    @url.setter
    def url(self, url: Any) -> None: ...
    @property
    def destroy_session(self): ...
    @destroy_session.setter
    def destroy_session(self, destroy_session: Any) -> None: ...
    @property
    def ajax(self): ...
    @ajax.setter
    def ajax(self, ajax: Any) -> None: ...
    @property
    def next(self): ...
    @next.setter
    def next(self, next: Any) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other: Any) -> Any: ...
    def __ne__(self, other: Any) -> Any: ...
