from typing import Any, Optional

class Mainnav:
    swagger_types: Any = ...
    attribute_map: Any = ...
    discriminator: Any = ...
    def __init__(self, icon: Optional[Any] = ..., main_menu_style: Optional[Any] = ...) -> None: ...
    @property
    def icon(self): ...
    @icon.setter
    def icon(self, icon: Any) -> None: ...
    @property
    def main_menu_style(self): ...
    @main_menu_style.setter
    def main_menu_style(self, main_menu_style: Any) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other: Any) -> Any: ...
    def __ne__(self, other: Any) -> Any: ...
