from typing import Any, Optional

class MdsFormPanel:
    swagger_types: Any = ...
    attribute_map: Any = ...
    discriminator: Any = ...
    def __init__(self, name: Optional[Any] = ..., style_name: Optional[Any] = ..., label: Optional[Any] = ..., layout: Optional[Any] = ..., on_create: bool = ..., on_update: bool = ..., multi_upload: bool = ..., order: Optional[Any] = ..., properties: Optional[Any] = ...) -> None: ...
    @property
    def name(self): ...
    @name.setter
    def name(self, name: Any) -> None: ...
    @property
    def style_name(self): ...
    @style_name.setter
    def style_name(self, style_name: Any) -> None: ...
    @property
    def label(self): ...
    @label.setter
    def label(self, label: Any) -> None: ...
    @property
    def layout(self): ...
    @layout.setter
    def layout(self, layout: Any) -> None: ...
    @property
    def on_create(self): ...
    @on_create.setter
    def on_create(self, on_create: Any) -> None: ...
    @property
    def on_update(self): ...
    @on_update.setter
    def on_update(self, on_update: Any) -> None: ...
    @property
    def multi_upload(self): ...
    @multi_upload.setter
    def multi_upload(self, multi_upload: Any) -> None: ...
    @property
    def order(self): ...
    @order.setter
    def order(self, order: Any) -> None: ...
    @property
    def properties(self): ...
    @properties.setter
    def properties(self, properties: Any) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other: Any) -> Any: ...
    def __ne__(self, other: Any) -> Any: ...
