from typing import Any, Optional

class MdsQueries:
    swagger_types: Any = ...
    attribute_map: Any = ...
    discriminator: Any = ...
    def __init__(self, base_query: Optional[Any] = ..., queries: Optional[Any] = ...) -> None: ...
    @property
    def base_query(self): ...
    @base_query.setter
    def base_query(self, base_query: Any) -> None: ...
    @property
    def queries(self): ...
    @queries.setter
    def queries(self, queries: Any) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other: Any) -> Any: ...
    def __ne__(self, other: Any) -> Any: ...
