from typing import Any, Optional

class MediacenterProfileExtension:
    swagger_types: Any = ...
    attribute_map: Any = ...
    discriminator: Any = ...
    def __init__(self, id: Optional[Any] = ..., location: Optional[Any] = ..., district_abbreviation: Optional[Any] = ..., main_url: Optional[Any] = ..., catalogs: Optional[Any] = ..., content_status: Optional[Any] = ...) -> None: ...
    @property
    def id(self): ...
    @id.setter
    def id(self, id: Any) -> None: ...
    @property
    def location(self): ...
    @location.setter
    def location(self, location: Any) -> None: ...
    @property
    def district_abbreviation(self): ...
    @district_abbreviation.setter
    def district_abbreviation(self, district_abbreviation: Any) -> None: ...
    @property
    def main_url(self): ...
    @main_url.setter
    def main_url(self, main_url: Any) -> None: ...
    @property
    def catalogs(self): ...
    @catalogs.setter
    def catalogs(self, catalogs: Any) -> None: ...
    @property
    def content_status(self): ...
    @content_status.setter
    def content_status(self, content_status: Any) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other: Any) -> Any: ...
    def __ne__(self, other: Any) -> Any: ...
