from typing import Any

class NodeLocked:
    swagger_types: Any = ...
    attribute_map: Any = ...
    discriminator: Any = ...
    def __init__(self, is_locked: bool = ...) -> None: ...
    @property
    def is_locked(self): ...
    @is_locked.setter
    def is_locked(self, is_locked: Any) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other: Any) -> Any: ...
    def __ne__(self, other: Any) -> Any: ...
