from typing import Any, Optional

class NodeVersion:
    swagger_types: Any = ...
    attribute_map: Any = ...
    discriminator: Any = ...
    def __init__(self, properties: Optional[Any] = ..., version: Optional[Any] = ..., comment: Optional[Any] = ..., modified_at: Optional[Any] = ..., modified_by: Optional[Any] = ..., content_url: Optional[Any] = ...) -> None: ...
    @property
    def properties(self): ...
    @properties.setter
    def properties(self, properties: Any) -> None: ...
    @property
    def version(self): ...
    @version.setter
    def version(self, version: Any) -> None: ...
    @property
    def comment(self): ...
    @comment.setter
    def comment(self, comment: Any) -> None: ...
    @property
    def modified_at(self): ...
    @modified_at.setter
    def modified_at(self, modified_at: Any) -> None: ...
    @property
    def modified_by(self): ...
    @modified_by.setter
    def modified_by(self, modified_by: Any) -> None: ...
    @property
    def content_url(self): ...
    @content_url.setter
    def content_url(self, content_url: Any) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other: Any) -> Any: ...
    def __ne__(self, other: Any) -> Any: ...
