from typing import Any, Optional

class NodeText:
    swagger_types: Any = ...
    attribute_map: Any = ...
    discriminator: Any = ...
    def __init__(self, text: Optional[Any] = ..., html: Optional[Any] = ..., raw: Optional[Any] = ...) -> None: ...
    @property
    def text(self): ...
    @text.setter
    def text(self, text: Any) -> None: ...
    @property
    def html(self): ...
    @html.setter
    def html(self, html: Any) -> None: ...
    @property
    def raw(self): ...
    @raw.setter
    def raw(self, raw: Any) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other: Any) -> Any: ...
    def __ne__(self, other: Any) -> Any: ...
