from typing import Any, Optional

class NodePermissions:
    swagger_types: Any = ...
    attribute_map: Any = ...
    discriminator: Any = ...
    def __init__(self, local_permissions: Optional[Any] = ..., inherited_permissions: Optional[Any] = ...) -> None: ...
    @property
    def local_permissions(self): ...
    @local_permissions.setter
    def local_permissions(self, local_permissions: Any) -> None: ...
    @property
    def inherited_permissions(self): ...
    @inherited_permissions.setter
    def inherited_permissions(self, inherited_permissions: Any) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other: Any) -> Any: ...
    def __ne__(self, other: Any) -> Any: ...
