from typing import Any, Optional

class NodeShare:
    swagger_types: Any = ...
    attribute_map: Any = ...
    discriminator: Any = ...
    def __init__(self, password: bool = ..., token: Optional[Any] = ..., email: Optional[Any] = ..., expiry_date: Optional[Any] = ..., invited_at: Optional[Any] = ..., download_count: Optional[Any] = ..., url: Optional[Any] = ..., share_id: Optional[Any] = ...) -> None: ...
    @property
    def password(self): ...
    @password.setter
    def password(self, password: Any) -> None: ...
    @property
    def token(self): ...
    @token.setter
    def token(self, token: Any) -> None: ...
    @property
    def email(self): ...
    @email.setter
    def email(self, email: Any) -> None: ...
    @property
    def expiry_date(self): ...
    @expiry_date.setter
    def expiry_date(self, expiry_date: Any) -> None: ...
    @property
    def invited_at(self): ...
    @invited_at.setter
    def invited_at(self, invited_at: Any) -> None: ...
    @property
    def download_count(self): ...
    @download_count.setter
    def download_count(self, download_count: Any) -> None: ...
    @property
    def url(self): ...
    @url.setter
    def url(self, url: Any) -> None: ...
    @property
    def share_id(self): ...
    @share_id.setter
    def share_id(self, share_id: Any) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other: Any) -> Any: ...
    def __ne__(self, other: Any) -> Any: ...
