from typing import Any, Optional

class NodeVersionRefEntries:
    swagger_types: Any = ...
    attribute_map: Any = ...
    discriminator: Any = ...
    def __init__(self, versions: Optional[Any] = ...) -> None: ...
    @property
    def versions(self): ...
    @versions.setter
    def versions(self, versions: Any) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other: Any) -> Any: ...
    def __ne__(self, other: Any) -> Any: ...
