from typing import Any, Optional

class NotifyEntry:
    swagger_types: Any = ...
    attribute_map: Any = ...
    discriminator: Any = ...
    def __init__(self, _date: Optional[Any] = ..., permissions: Optional[Any] = ..., user: Optional[Any] = ..., action: Optional[Any] = ...) -> None: ...
    @property
    def permissions(self): ...
    @permissions.setter
    def permissions(self, permissions: Any) -> None: ...
    @property
    def user(self): ...
    @user.setter
    def user(self, user: Any) -> None: ...
    @property
    def action(self): ...
    @action.setter
    def action(self, action: Any) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other: Any) -> Any: ...
    def __ne__(self, other: Any) -> Any: ...
