from typing import Any, Optional

class OrganizationEntries:
    swagger_types: Any = ...
    attribute_map: Any = ...
    discriminator: Any = ...
    def __init__(self, organizations: Optional[Any] = ..., pagination: Optional[Any] = ..., can_create: bool = ...) -> None: ...
    @property
    def organizations(self): ...
    @organizations.setter
    def organizations(self, organizations: Any) -> None: ...
    @property
    def pagination(self): ...
    @pagination.setter
    def pagination(self, pagination: Any) -> None: ...
    @property
    def can_create(self): ...
    @can_create.setter
    def can_create(self, can_create: Any) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other: Any) -> Any: ...
    def __ne__(self, other: Any) -> Any: ...
