from typing import Any, Optional

class Parameters:
    swagger_types: Any = ...
    attribute_map: Any = ...
    discriminator: Any = ...
    def __init__(self, general: Optional[Any] = ...) -> None: ...
    @property
    def general(self): ...
    @general.setter
    def general(self, general: Any) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other: Any) -> Any: ...
    def __ne__(self, other: Any) -> Any: ...
