from typing import Any, Optional

class PersonDeleteOptions:
    swagger_types: Any = ...
    attribute_map: Any = ...
    discriminator: Any = ...
    def __init__(self, cleanup_metadata: bool = ..., home_folder: Optional[Any] = ..., shared_folders: Optional[Any] = ..., collections: Optional[Any] = ..., ratings: Optional[Any] = ..., comments: Optional[Any] = ..., collection_feedback: Optional[Any] = ..., statistics: Optional[Any] = ..., stream: Optional[Any] = ..., receiver: Optional[Any] = ..., receiver_group: Optional[Any] = ...) -> None: ...
    @property
    def cleanup_metadata(self): ...
    @cleanup_metadata.setter
    def cleanup_metadata(self, cleanup_metadata: Any) -> None: ...
    @property
    def home_folder(self): ...
    @home_folder.setter
    def home_folder(self, home_folder: Any) -> None: ...
    @property
    def shared_folders(self): ...
    @shared_folders.setter
    def shared_folders(self, shared_folders: Any) -> None: ...
    @property
    def collections(self): ...
    @collections.setter
    def collections(self, collections: Any) -> None: ...
    @property
    def ratings(self): ...
    @ratings.setter
    def ratings(self, ratings: Any) -> None: ...
    @property
    def comments(self): ...
    @comments.setter
    def comments(self, comments: Any) -> None: ...
    @property
    def collection_feedback(self): ...
    @collection_feedback.setter
    def collection_feedback(self, collection_feedback: Any) -> None: ...
    @property
    def statistics(self): ...
    @statistics.setter
    def statistics(self, statistics: Any) -> None: ...
    @property
    def stream(self): ...
    @stream.setter
    def stream(self, stream: Any) -> None: ...
    @property
    def receiver(self): ...
    @receiver.setter
    def receiver(self, receiver: Any) -> None: ...
    @property
    def receiver_group(self): ...
    @receiver_group.setter
    def receiver_group(self, receiver_group: Any) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other: Any) -> Any: ...
    def __ne__(self, other: Any) -> Any: ...
