from typing import Any, Optional

class PersonReport:
    swagger_types: Any = ...
    attribute_map: Any = ...
    discriminator: Any = ...
    def __init__(self, options: Optional[Any] = ..., results: Optional[Any] = ...) -> None: ...
    @property
    def options(self): ...
    @options.setter
    def options(self, options: Any) -> None: ...
    @property
    def results(self): ...
    @results.setter
    def results(self, results: Any) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other: Any) -> Any: ...
    def __ne__(self, other: Any) -> Any: ...
