from typing import Any, Optional

class Preferences:
    swagger_types: Any = ...
    attribute_map: Any = ...
    discriminator: Any = ...
    def __init__(self, preferences: Optional[Any] = ...) -> None: ...
    @property
    def preferences(self): ...
    @preferences.setter
    def preferences(self, preferences: Any) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other: Any) -> Any: ...
    def __ne__(self, other: Any) -> Any: ...
