from typing import Any, Optional

class Preview:
    swagger_types: Any = ...
    attribute_map: Any = ...
    discriminator: Any = ...
    def __init__(self, is_icon: bool = ..., is_generated: bool = ..., url: Optional[Any] = ..., width: Optional[Any] = ..., height: Optional[Any] = ...) -> None: ...
    @property
    def is_icon(self): ...
    @is_icon.setter
    def is_icon(self, is_icon: Any) -> None: ...
    @property
    def is_generated(self): ...
    @is_generated.setter
    def is_generated(self, is_generated: Any) -> None: ...
    @property
    def url(self): ...
    @url.setter
    def url(self, url: Any) -> None: ...
    @property
    def width(self): ...
    @width.setter
    def width(self, width: Any) -> None: ...
    @property
    def height(self): ...
    @height.setter
    def height(self, height: Any) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other: Any) -> Any: ...
    def __ne__(self, other: Any) -> Any: ...
