from typing import Any, Optional

class Query:
    swagger_types: Any = ...
    attribute_map: Any = ...
    discriminator: Any = ...
    def __init__(self, condition: Optional[Any] = ..., query: Optional[Any] = ...) -> None: ...
    @property
    def condition(self): ...
    @condition.setter
    def condition(self, condition: Any) -> None: ...
    @property
    def query(self): ...
    @query.setter
    def query(self, query: Any) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other: Any) -> Any: ...
    def __ne__(self, other: Any) -> Any: ...
