from typing import Any, Optional

class RatingData:
    swagger_types: Any = ...
    attribute_map: Any = ...
    discriminator: Any = ...
    def __init__(self, sum: Optional[Any] = ..., count: Optional[Any] = ..., rating: Optional[Any] = ...) -> None: ...
    @property
    def sum(self): ...
    @sum.setter
    def sum(self, sum: Any) -> None: ...
    @property
    def count(self): ...
    @count.setter
    def count(self, count: Any) -> None: ...
    @property
    def rating(self): ...
    @rating.setter
    def rating(self, rating: Any) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other: Any) -> Any: ...
    def __ne__(self, other: Any) -> Any: ...
