from typing import Any, Optional

class Register:
    swagger_types: Any = ...
    attribute_map: Any = ...
    discriminator: Any = ...
    def __init__(self, local: bool = ..., login_url: Optional[Any] = ..., recover_url: Optional[Any] = ..., required_fields: Optional[Any] = ...) -> None: ...
    @property
    def local(self): ...
    @local.setter
    def local(self, local: Any) -> None: ...
    @property
    def login_url(self): ...
    @login_url.setter
    def login_url(self, login_url: Any) -> None: ...
    @property
    def recover_url(self): ...
    @recover_url.setter
    def recover_url(self, recover_url: Any) -> None: ...
    @property
    def required_fields(self): ...
    @required_fields.setter
    def required_fields(self, required_fields: Any) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other: Any) -> Any: ...
    def __ne__(self, other: Any) -> Any: ...
