from typing import Any

class RegisterExists:
    swagger_types: Any = ...
    attribute_map: Any = ...
    discriminator: Any = ...
    def __init__(self, exists: bool = ...) -> None: ...
    @property
    def exists(self): ...
    @exists.setter
    def exists(self, exists: Any) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other: Any) -> Any: ...
    def __ne__(self, other: Any) -> Any: ...
