from typing import Any, Optional

class Remote:
    swagger_types: Any = ...
    attribute_map: Any = ...
    discriminator: Any = ...
    def __init__(self, repository: Optional[Any] = ..., id: Optional[Any] = ...) -> None: ...
    @property
    def repository(self): ...
    @repository.setter
    def repository(self, repository: Any) -> None: ...
    @property
    def id(self): ...
    @id.setter
    def id(self, id: Any) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other: Any) -> Any: ...
    def __ne__(self, other: Any) -> Any: ...
