from typing import Any, Optional

class RenderingDetailsEntry:
    swagger_types: Any = ...
    attribute_map: Any = ...
    discriminator: Any = ...
    def __init__(self, details_snippet: Optional[Any] = ..., mime_type: Optional[Any] = ..., node: Optional[Any] = ...) -> None: ...
    @property
    def details_snippet(self): ...
    @details_snippet.setter
    def details_snippet(self, details_snippet: Any) -> None: ...
    @property
    def mime_type(self): ...
    @mime_type.setter
    def mime_type(self, mime_type: Any) -> None: ...
    @property
    def node(self): ...
    @node.setter
    def node(self, node: Any) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other: Any) -> Any: ...
    def __ne__(self, other: Any) -> Any: ...
