from typing import Any, Optional

class SimpleEdit:
    swagger_types: Any = ...
    attribute_map: Any = ...
    discriminator: Any = ...
    def __init__(self, global_groups: Optional[Any] = ..., organization: Optional[Any] = ...) -> None: ...
    @property
    def global_groups(self): ...
    @global_groups.setter
    def global_groups(self, global_groups: Any) -> None: ...
    @property
    def organization(self): ...
    @organization.setter
    def organization(self, organization: Any) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other: Any) -> Any: ...
    def __ne__(self, other: Any) -> Any: ...
