from typing import Any, Optional

class SortV2Default:
    swagger_types: Any = ...
    attribute_map: Any = ...
    discriminator: Any = ...
    def __init__(self, sort_by: Optional[Any] = ..., sort_ascending: bool = ...) -> None: ...
    @property
    def sort_by(self): ...
    @sort_by.setter
    def sort_by(self, sort_by: Any) -> None: ...
    @property
    def sort_ascending(self): ...
    @sort_ascending.setter
    def sort_ascending(self, sort_ascending: Any) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other: Any) -> Any: ...
    def __ne__(self, other: Any) -> Any: ...
