from typing import Any, Optional

class StatisticEntry:
    swagger_types: Any = ...
    attribute_map: Any = ...
    discriminator: Any = ...
    def __init__(self, _property: Optional[Any] = ..., entities: Optional[Any] = ...) -> None: ...
    @property
    def entities(self): ...
    @entities.setter
    def entities(self, entities: Any) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other: Any) -> Any: ...
    def __ne__(self, other: Any) -> Any: ...
