from typing import Any, Optional

class StatisticsGroup:
    swagger_types: Any = ...
    attribute_map: Any = ...
    discriminator: Any = ...
    def __init__(self, count: Optional[Any] = ..., sub_groups: Optional[Any] = ...) -> None: ...
    @property
    def count(self): ...
    @count.setter
    def count(self, count: Any) -> None: ...
    @property
    def sub_groups(self): ...
    @sub_groups.setter
    def sub_groups(self, sub_groups: Any) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other: Any) -> Any: ...
    def __ne__(self, other: Any) -> Any: ...
