from typing import Any

class Stream:
    swagger_types: Any = ...
    attribute_map: Any = ...
    discriminator: Any = ...
    def __init__(self, enabled: bool = ...) -> None: ...
    @property
    def enabled(self): ...
    @enabled.setter
    def enabled(self, enabled: Any) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other: Any) -> Any: ...
    def __ne__(self, other: Any) -> Any: ...
