from typing import Any, Optional

class SuggestionParam:
    swagger_types: Any = ...
    attribute_map: Any = ...
    discriminator: Any = ...
    def __init__(self, value_parameters: Optional[Any] = ..., criterias: Optional[Any] = ...) -> None: ...
    @property
    def value_parameters(self): ...
    @value_parameters.setter
    def value_parameters(self, value_parameters: Any) -> None: ...
    @property
    def criterias(self): ...
    @criterias.setter
    def criterias(self, criterias: Any) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other: Any) -> Any: ...
    def __ne__(self, other: Any) -> Any: ...
