from typing import Any, Optional

class UserSimple:
    swagger_types: Any = ...
    attribute_map: Any = ...
    discriminator: Any = ...
    def __init__(self, status: Optional[Any] = ..., authority_name: Optional[Any] = ..., authority_type: Optional[Any] = ..., user_name: Optional[Any] = ..., profile: Optional[Any] = ..., stats: Optional[Any] = ...) -> None: ...
    @property
    def status(self): ...
    @status.setter
    def status(self, status: Any) -> None: ...
    @property
    def authority_name(self): ...
    @authority_name.setter
    def authority_name(self, authority_name: Any) -> None: ...
    @property
    def authority_type(self): ...
    @authority_type.setter
    def authority_type(self, authority_type: Any) -> None: ...
    @property
    def user_name(self): ...
    @user_name.setter
    def user_name(self, user_name: Any) -> None: ...
    @property
    def profile(self): ...
    @profile.setter
    def profile(self, profile: Any) -> None: ...
    @property
    def stats(self): ...
    @stats.setter
    def stats(self, stats: Any) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other: Any) -> Any: ...
    def __ne__(self, other: Any) -> Any: ...
