from typing import Any, Optional

class UserCredential:
    swagger_types: Any = ...
    attribute_map: Any = ...
    discriminator: Any = ...
    def __init__(self, old_password: Optional[Any] = ..., new_password: Optional[Any] = ...) -> None: ...
    @property
    def old_password(self): ...
    @old_password.setter
    def old_password(self, old_password: Any) -> None: ...
    @property
    def new_password(self): ...
    @new_password.setter
    def new_password(self, new_password: Any) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other: Any) -> Any: ...
    def __ne__(self, other: Any) -> Any: ...
