from typing import Any, Optional

class UserEntries:
    swagger_types: Any = ...
    attribute_map: Any = ...
    discriminator: Any = ...
    def __init__(self, users: Optional[Any] = ..., pagination: Optional[Any] = ...) -> None: ...
    @property
    def users(self): ...
    @users.setter
    def users(self, users: Any) -> None: ...
    @property
    def pagination(self): ...
    @pagination.setter
    def pagination(self, pagination: Any) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other: Any) -> Any: ...
    def __ne__(self, other: Any) -> Any: ...
