from typing import Any, Optional

class UserQuota:
    swagger_types: Any = ...
    attribute_map: Any = ...
    discriminator: Any = ...
    def __init__(self, enabled: bool = ..., size_current: Optional[Any] = ..., size_quota: Optional[Any] = ...) -> None: ...
    @property
    def enabled(self): ...
    @enabled.setter
    def enabled(self, enabled: Any) -> None: ...
    @property
    def size_current(self): ...
    @size_current.setter
    def size_current(self, size_current: Any) -> None: ...
    @property
    def size_quota(self): ...
    @size_quota.setter
    def size_quota(self, size_quota: Any) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other: Any) -> Any: ...
    def __ne__(self, other: Any) -> Any: ...
