from typing import Any, Optional

class UserEntry:
    swagger_types: Any = ...
    attribute_map: Any = ...
    discriminator: Any = ...
    def __init__(self, edit_profile: bool = ..., person: Optional[Any] = ...) -> None: ...
    @property
    def edit_profile(self): ...
    @edit_profile.setter
    def edit_profile(self, edit_profile: Any) -> None: ...
    @property
    def person(self): ...
    @person.setter
    def person(self, person: Any) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other: Any) -> Any: ...
    def __ne__(self, other: Any) -> Any: ...
