from typing import Any, Optional

class UserStats:
    swagger_types: Any = ...
    attribute_map: Any = ...
    discriminator: Any = ...
    def __init__(self, node_count: Optional[Any] = ..., node_count_cc: Optional[Any] = ..., collection_count: Optional[Any] = ...) -> None: ...
    @property
    def node_count(self): ...
    @node_count.setter
    def node_count(self, node_count: Any) -> None: ...
    @property
    def node_count_cc(self): ...
    @node_count_cc.setter
    def node_count_cc(self, node_count_cc: Any) -> None: ...
    @property
    def collection_count(self): ...
    @collection_count.setter
    def collection_count(self, collection_count: Any) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other: Any) -> Any: ...
    def __ne__(self, other: Any) -> Any: ...
