from typing import Any, Optional

class Values:
    swagger_types: Any = ...
    attribute_map: Any = ...
    discriminator: Any = ...
    def __init__(self, supported_languages: Optional[Any] = ..., extension: Optional[Any] = ..., login_url: Optional[Any] = ..., login_allow_local: bool = ..., login_providers_url: Optional[Any] = ..., login_provider_target_url: Optional[Any] = ..., register: Optional[Any] = ..., recover_password_url: Optional[Any] = ..., imprint_url: Optional[Any] = ..., privacy_information_url: Optional[Any] = ..., help_url: Optional[Any] = ..., whats_new_url: Optional[Any] = ..., edit_profile_url: Optional[Any] = ..., edit_profile: bool = ..., workspace_columns: Optional[Any] = ..., hide_main_menu: Optional[Any] = ..., logout: Optional[Any] = ..., menu_entries: Optional[Any] = ..., node_options: Optional[Any] = ..., search_node_options: Optional[Any] = ..., render_node_options: Optional[Any] = ..., collection_node_options: Optional[Any] = ..., node_store_options: Optional[Any] = ..., allowed_licenses: Optional[Any] = ..., custom_licenses: Optional[Any] = ..., workflows: Optional[Any] = ..., license_dialog_on_upload: bool = ..., node_report: bool = ..., branding: bool = ..., publishing_notice: bool = ..., site_title: Optional[Any] = ..., user_display_name: Optional[Any] = ..., user_secondary_display_name: Optional[Any] = ..., user_affiliation: bool = ..., default_username: Optional[Any] = ..., default_password: Optional[Any] = ..., banner: Optional[Any] = ..., available_mds: Optional[Any] = ..., available_repositories: Optional[Any] = ..., search_view_type: Optional[Any] = ..., items_per_request: Optional[Any] = ..., rendering: Optional[Any] = ..., session_expired_dialog: Optional[Any] = ..., login_default_location: Optional[Any] = ..., search_group_results: bool = ..., mainnav: Optional[Any] = ..., search_sidenav_mode: Optional[Any] = ..., guest: Optional[Any] = ..., collections: Optional[Any] = ..., license_agreement: Optional[Any] = ..., services: Optional[Any] = ..., help_menu_options: Optional[Any] = ..., images: Optional[Any] = ..., stream: Optional[Any] = ..., admin: Optional[Any] = ..., simple_edit: Optional[Any] = ...) -> None: ...
    @property
    def supported_languages(self): ...
    @supported_languages.setter
    def supported_languages(self, supported_languages: Any) -> None: ...
    @property
    def extension(self): ...
    @extension.setter
    def extension(self, extension: Any) -> None: ...
    @property
    def login_url(self): ...
    @login_url.setter
    def login_url(self, login_url: Any) -> None: ...
    @property
    def login_allow_local(self): ...
    @login_allow_local.setter
    def login_allow_local(self, login_allow_local: Any) -> None: ...
    @property
    def login_providers_url(self): ...
    @login_providers_url.setter
    def login_providers_url(self, login_providers_url: Any) -> None: ...
    @property
    def login_provider_target_url(self): ...
    @login_provider_target_url.setter
    def login_provider_target_url(self, login_provider_target_url: Any) -> None: ...
    @property
    def register(self): ...
    @register.setter
    def register(self, register: Any) -> None: ...
    @property
    def recover_password_url(self): ...
    @recover_password_url.setter
    def recover_password_url(self, recover_password_url: Any) -> None: ...
    @property
    def imprint_url(self): ...
    @imprint_url.setter
    def imprint_url(self, imprint_url: Any) -> None: ...
    @property
    def privacy_information_url(self): ...
    @privacy_information_url.setter
    def privacy_information_url(self, privacy_information_url: Any) -> None: ...
    @property
    def help_url(self): ...
    @help_url.setter
    def help_url(self, help_url: Any) -> None: ...
    @property
    def whats_new_url(self): ...
    @whats_new_url.setter
    def whats_new_url(self, whats_new_url: Any) -> None: ...
    @property
    def edit_profile_url(self): ...
    @edit_profile_url.setter
    def edit_profile_url(self, edit_profile_url: Any) -> None: ...
    @property
    def edit_profile(self): ...
    @edit_profile.setter
    def edit_profile(self, edit_profile: Any) -> None: ...
    @property
    def workspace_columns(self): ...
    @workspace_columns.setter
    def workspace_columns(self, workspace_columns: Any) -> None: ...
    @property
    def hide_main_menu(self): ...
    @hide_main_menu.setter
    def hide_main_menu(self, hide_main_menu: Any) -> None: ...
    @property
    def logout(self): ...
    @logout.setter
    def logout(self, logout: Any) -> None: ...
    @property
    def menu_entries(self): ...
    @menu_entries.setter
    def menu_entries(self, menu_entries: Any) -> None: ...
    @property
    def node_options(self): ...
    @node_options.setter
    def node_options(self, node_options: Any) -> None: ...
    @property
    def search_node_options(self): ...
    @search_node_options.setter
    def search_node_options(self, search_node_options: Any) -> None: ...
    @property
    def render_node_options(self): ...
    @render_node_options.setter
    def render_node_options(self, render_node_options: Any) -> None: ...
    @property
    def collection_node_options(self): ...
    @collection_node_options.setter
    def collection_node_options(self, collection_node_options: Any) -> None: ...
    @property
    def node_store_options(self): ...
    @node_store_options.setter
    def node_store_options(self, node_store_options: Any) -> None: ...
    @property
    def allowed_licenses(self): ...
    @allowed_licenses.setter
    def allowed_licenses(self, allowed_licenses: Any) -> None: ...
    @property
    def custom_licenses(self): ...
    @custom_licenses.setter
    def custom_licenses(self, custom_licenses: Any) -> None: ...
    @property
    def workflows(self): ...
    @workflows.setter
    def workflows(self, workflows: Any) -> None: ...
    @property
    def license_dialog_on_upload(self): ...
    @license_dialog_on_upload.setter
    def license_dialog_on_upload(self, license_dialog_on_upload: Any) -> None: ...
    @property
    def node_report(self): ...
    @node_report.setter
    def node_report(self, node_report: Any) -> None: ...
    @property
    def branding(self): ...
    @branding.setter
    def branding(self, branding: Any) -> None: ...
    @property
    def publishing_notice(self): ...
    @publishing_notice.setter
    def publishing_notice(self, publishing_notice: Any) -> None: ...
    @property
    def site_title(self): ...
    @site_title.setter
    def site_title(self, site_title: Any) -> None: ...
    @property
    def user_display_name(self): ...
    @user_display_name.setter
    def user_display_name(self, user_display_name: Any) -> None: ...
    @property
    def user_secondary_display_name(self): ...
    @user_secondary_display_name.setter
    def user_secondary_display_name(self, user_secondary_display_name: Any) -> None: ...
    @property
    def user_affiliation(self): ...
    @user_affiliation.setter
    def user_affiliation(self, user_affiliation: Any) -> None: ...
    @property
    def default_username(self): ...
    @default_username.setter
    def default_username(self, default_username: Any) -> None: ...
    @property
    def default_password(self): ...
    @default_password.setter
    def default_password(self, default_password: Any) -> None: ...
    @property
    def banner(self): ...
    @banner.setter
    def banner(self, banner: Any) -> None: ...
    @property
    def available_mds(self): ...
    @available_mds.setter
    def available_mds(self, available_mds: Any) -> None: ...
    @property
    def available_repositories(self): ...
    @available_repositories.setter
    def available_repositories(self, available_repositories: Any) -> None: ...
    @property
    def search_view_type(self): ...
    @search_view_type.setter
    def search_view_type(self, search_view_type: Any) -> None: ...
    @property
    def items_per_request(self): ...
    @items_per_request.setter
    def items_per_request(self, items_per_request: Any) -> None: ...
    @property
    def rendering(self): ...
    @rendering.setter
    def rendering(self, rendering: Any) -> None: ...
    @property
    def session_expired_dialog(self): ...
    @session_expired_dialog.setter
    def session_expired_dialog(self, session_expired_dialog: Any) -> None: ...
    @property
    def login_default_location(self): ...
    @login_default_location.setter
    def login_default_location(self, login_default_location: Any) -> None: ...
    @property
    def search_group_results(self): ...
    @search_group_results.setter
    def search_group_results(self, search_group_results: Any) -> None: ...
    @property
    def mainnav(self): ...
    @mainnav.setter
    def mainnav(self, mainnav: Any) -> None: ...
    @property
    def search_sidenav_mode(self): ...
    @search_sidenav_mode.setter
    def search_sidenav_mode(self, search_sidenav_mode: Any) -> None: ...
    @property
    def guest(self): ...
    @guest.setter
    def guest(self, guest: Any) -> None: ...
    @property
    def collections(self): ...
    @collections.setter
    def collections(self, collections: Any) -> None: ...
    @property
    def license_agreement(self): ...
    @license_agreement.setter
    def license_agreement(self, license_agreement: Any) -> None: ...
    @property
    def services(self): ...
    @services.setter
    def services(self, services: Any) -> None: ...
    @property
    def help_menu_options(self): ...
    @help_menu_options.setter
    def help_menu_options(self, help_menu_options: Any) -> None: ...
    @property
    def images(self): ...
    @images.setter
    def images(self, images: Any) -> None: ...
    @property
    def stream(self): ...
    @stream.setter
    def stream(self, stream: Any) -> None: ...
    @property
    def admin(self): ...
    @admin.setter
    def admin(self, admin: Any) -> None: ...
    @property
    def simple_edit(self): ...
    @simple_edit.setter
    def simple_edit(self, simple_edit: Any) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other: Any) -> Any: ...
    def __ne__(self, other: Any) -> Any: ...
