from typing import Any, Optional

class ValueParameters:
    swagger_types: Any = ...
    attribute_map: Any = ...
    discriminator: Any = ...
    def __init__(self, query: Optional[Any] = ..., _property: Optional[Any] = ..., pattern: Optional[Any] = ...) -> None: ...
    @property
    def query(self): ...
    @query.setter
    def query(self, query: Any) -> None: ...
    @property
    def pattern(self): ...
    @pattern.setter
    def pattern(self, pattern: Any) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other: Any) -> Any: ...
    def __ne__(self, other: Any) -> Any: ...
