from typing import Any, Optional

class Variables:
    swagger_types: Any = ...
    attribute_map: Any = ...
    discriminator: Any = ...
    def __init__(self, _global: Optional[Any] = ..., current: Optional[Any] = ...) -> None: ...
    @property
    def current(self): ...
    @current.setter
    def current(self, current: Any) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other: Any) -> Any: ...
    def __ne__(self, other: Any) -> Any: ...
