from typing import Any, Optional

class ViewV2:
    swagger_types: Any = ...
    attribute_map: Any = ...
    discriminator: Any = ...
    def __init__(self, id: Optional[Any] = ..., caption: Optional[Any] = ..., icon: Optional[Any] = ..., html: Optional[Any] = ..., rel: Optional[Any] = ..., hide_if_empty: bool = ...) -> None: ...
    @property
    def id(self): ...
    @id.setter
    def id(self, id: Any) -> None: ...
    @property
    def caption(self): ...
    @caption.setter
    def caption(self, caption: Any) -> None: ...
    @property
    def icon(self): ...
    @icon.setter
    def icon(self, icon: Any) -> None: ...
    @property
    def html(self): ...
    @html.setter
    def html(self, html: Any) -> None: ...
    @property
    def rel(self): ...
    @rel.setter
    def rel(self, rel: Any) -> None: ...
    @property
    def hide_if_empty(self): ...
    @hide_if_empty.setter
    def hide_if_empty(self, hide_if_empty: Any) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other: Any) -> Any: ...
    def __ne__(self, other: Any) -> Any: ...
