from typing import Any, Optional

class WebsiteInformation:
    swagger_types: Any = ...
    attribute_map: Any = ...
    discriminator: Any = ...
    def __init__(self, title: Optional[Any] = ..., page: Optional[Any] = ..., description: Optional[Any] = ..., license: Optional[Any] = ..., keywords: Optional[Any] = ...) -> None: ...
    @property
    def title(self): ...
    @title.setter
    def title(self, title: Any) -> None: ...
    @property
    def page(self): ...
    @page.setter
    def page(self, page: Any) -> None: ...
    @property
    def description(self): ...
    @description.setter
    def description(self, description: Any) -> None: ...
    @property
    def license(self): ...
    @license.setter
    def license(self, license: Any) -> None: ...
    @property
    def keywords(self): ...
    @keywords.setter
    def keywords(self, keywords: Any) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other: Any) -> Any: ...
    def __ne__(self, other: Any) -> Any: ...
