from typing import Any, Optional

class WorkflowHistory:
    swagger_types: Any = ...
    attribute_map: Any = ...
    discriminator: Any = ...
    def __init__(self, time: Optional[Any] = ..., editor: Optional[Any] = ..., receiver: Optional[Any] = ..., status: Optional[Any] = ..., comment: Optional[Any] = ...) -> None: ...
    @property
    def time(self): ...
    @time.setter
    def time(self, time: Any) -> None: ...
    @property
    def editor(self): ...
    @editor.setter
    def editor(self, editor: Any) -> None: ...
    @property
    def receiver(self): ...
    @receiver.setter
    def receiver(self, receiver: Any) -> None: ...
    @property
    def status(self): ...
    @status.setter
    def status(self, status: Any) -> None: ...
    @property
    def comment(self): ...
    @comment.setter
    def comment(self, comment: Any) -> None: ...
    def to_dict(self): ...
    def to_str(self): ...
    def __eq__(self, other: Any) -> Any: ...
    def __ne__(self, other: Any) -> Any: ...
