from scrapy.contracts import Contract as Contract
from scrapy.exceptions import ContractFail as ContractFail
from scrapy.http import Request as Request
from typing import Any

class UrlContract(Contract):
    name: str = ...
    def adjust_request_args(self, args: Any): ...

class CallbackKeywordArgumentsContract(Contract):
    name: str = ...
    def adjust_request_args(self, args: Any): ...

class ReturnsContract(Contract):
    name: str = ...
    object_type_verifiers: Any = ...
    obj_name: Any = ...
    obj_type_verifier: Any = ...
    min_bound: Any = ...
    max_bound: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def post_process(self, output: Any) -> None: ...

class ScrapesContract(Contract):
    name: str = ...
    def post_process(self, output: Any) -> None: ...
