from scrapy.http.common import obsolete_setter as obsolete_setter
from scrapy.http.headers import Headers as Headers
from scrapy.utils.curl import curl_to_request_kwargs as curl_to_request_kwargs
from scrapy.utils.python import to_bytes as to_bytes
from scrapy.utils.trackref import object_ref as object_ref
from scrapy.utils.url import escape_ajax as escape_ajax
from typing import Any, Optional

class Request(object_ref):
    method: Any = ...
    priority: Any = ...
    callback: Any = ...
    errback: Any = ...
    cookies: Any = ...
    headers: Any = ...
    dont_filter: Any = ...
    flags: Any = ...
    def __init__(self, url: Any, callback: Optional[Any] = ..., method: str = ..., headers: Optional[Any] = ..., body: Optional[Any] = ..., cookies: Optional[Any] = ..., meta: Optional[Any] = ..., encoding: str = ..., priority: int = ..., dont_filter: bool = ..., errback: Optional[Any] = ..., flags: Optional[Any] = ..., cb_kwargs: Optional[Any] = ...) -> None: ...
    @property
    def cb_kwargs(self): ...
    @property
    def meta(self): ...
    url: Any = ...
    body: Any = ...
    @property
    def encoding(self): ...
    def copy(self): ...
    def replace(self, *args: Any, **kwargs: Any): ...
    @classmethod
    def from_curl(cls, curl_command: Any, ignore_unknown_options: bool = ..., **kwargs: Any): ...
