# coding: utf-8

"""
    edu-sharing Repository REST API

    The public restful API of the edu-sharing repository.  # noqa: E501

    OpenAPI spec version: 1.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class LogEntry(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'class_name': 'str',
        'level': 'Level',
        '_date': 'int',
        'message': 'str'
    }

    attribute_map = {
        'class_name': 'className',
        'level': 'level',
        '_date': 'date',
        'message': 'message'
    }

    def __init__(self, class_name=None, level=None, _date=None, message=None):  # noqa: E501
        """LogEntry - a model defined in Swagger"""  # noqa: E501
        self._class_name = None
        self._level = None
        self.__date = None
        self._message = None
        self.discriminator = None
        if class_name is not None:
            self.class_name = class_name
        if level is not None:
            self.level = level
        if _date is not None:
            self._date = _date
        if message is not None:
            self.message = message

    @property
    def class_name(self):
        """Gets the class_name of this LogEntry.  # noqa: E501


        :return: The class_name of this LogEntry.  # noqa: E501
        :rtype: str
        """
        return self._class_name

    @class_name.setter
    def class_name(self, class_name):
        """Sets the class_name of this LogEntry.


        :param class_name: The class_name of this LogEntry.  # noqa: E501
        :type: str
        """

        self._class_name = class_name

    @property
    def level(self):
        """Gets the level of this LogEntry.  # noqa: E501


        :return: The level of this LogEntry.  # noqa: E501
        :rtype: Level
        """
        return self._level

    @level.setter
    def level(self, level):
        """Sets the level of this LogEntry.


        :param level: The level of this LogEntry.  # noqa: E501
        :type: Level
        """

        self._level = level

    @property
    def _date(self):
        """Gets the _date of this LogEntry.  # noqa: E501


        :return: The _date of this LogEntry.  # noqa: E501
        :rtype: int
        """
        return self.__date

    @_date.setter
    def _date(self, _date):
        """Sets the _date of this LogEntry.


        :param _date: The _date of this LogEntry.  # noqa: E501
        :type: int
        """

        self.__date = _date

    @property
    def message(self):
        """Gets the message of this LogEntry.  # noqa: E501


        :return: The message of this LogEntry.  # noqa: E501
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message):
        """Sets the message of this LogEntry.


        :param message: The message of this LogEntry.  # noqa: E501
        :type: str
        """

        self._message = message

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(LogEntry, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, LogEntry):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
