from edu_sharing_client.api.about_api import ABOUTApi as ABOUTApi
from edu_sharing_client.api.admin_v1_api import ADMINV1Api as ADMINV1Api
from edu_sharing_client.api.archive_v1_api import ARCHIVEV1Api as ARCHIVEV1Api
from edu_sharing_client.api.authentication_v1_api import AUTHENTICATIONV1Api as AUTHENTICATIONV1Api
from edu_sharing_client.api.bulk_v1_api import BULKV1Api as BULKV1Api
from edu_sharing_client.api.clientutils_v1_api import CLIENTUTILSV1Api as CLIENTUTILSV1Api
from edu_sharing_client.api.collection_v1_api import COLLECTIONV1Api as COLLECTIONV1Api
from edu_sharing_client.api.comment_v1_api import COMMENTV1Api as COMMENTV1Api
from edu_sharing_client.api.config_v1_api import CONFIGV1Api as CONFIGV1Api
from edu_sharing_client.api.connector_v1_api import CONNECTORV1Api as CONNECTORV1Api
from edu_sharing_client.api.iam_v1_api import IAMV1Api as IAMV1Api
from edu_sharing_client.api.mds_v1_api import MDSV1Api as MDSV1Api
from edu_sharing_client.api.mediacenter_v1_api import MEDIACENTERV1Api as MEDIACENTERV1Api
from edu_sharing_client.api.network_v1_api import NETWORKV1Api as NETWORKV1Api
from edu_sharing_client.api.node_v1_api import NODEV1Api as NODEV1Api
from edu_sharing_client.api.organization_v1_api import ORGANIZATIONV1Api as ORGANIZATIONV1Api
from edu_sharing_client.api.rating_v1_api import RATINGV1Api as RATINGV1Api
from edu_sharing_client.api.register_v1_api import REGISTERV1Api as REGISTERV1Api
from edu_sharing_client.api.rendering_v1_api import RENDERINGV1Api as RENDERINGV1Api
from edu_sharing_client.api.search_v1_api import SEARCHV1Api as SEARCHV1Api
from edu_sharing_client.api.sharing_v1_api import SHARINGV1Api as SHARINGV1Api
from edu_sharing_client.api.statistic_v1_api import STATISTICV1Api as STATISTICV1Api
from edu_sharing_client.api.stream_v1_api import STREAMV1Api as STREAMV1Api
from edu_sharing_client.api.tool_v1_api import TOOLV1Api as TOOLV1Api
from edu_sharing_client.api.tracking_v1_api import TRACKINGV1Api as TRACKINGV1Api
from edu_sharing_client.api.usage_v1_api import USAGEV1Api as USAGEV1Api
