from edu_sharing_client.api_client import ApiClient as ApiClient
from typing import Any, Optional

class ABOUTApi:
    api_client: Any = ...
    def __init__(self, api_client: Optional[Any] = ...) -> None: ...
    def about(self, **kwargs: Any): ...
    def about_with_http_info(self, **kwargs: Any): ...
    def status(self, mode: Any, **kwargs: Any): ...
    def status_with_http_info(self, mode: Any, **kwargs: Any): ...
