from edu_sharing_client.api_client import ApiClient as ApiClient
from typing import Any, Optional

class ARCHIVEV1Api:
    api_client: Any = ...
    def __init__(self, api_client: Optional[Any] = ...) -> None: ...
    def purge(self, repository: Any, archived_node_ids: Any, **kwargs: Any): ...
    def purge_with_http_info(self, repository: Any, archived_node_ids: Any, **kwargs: Any): ...
    def restore(self, repository: Any, archived_node_ids: Any, **kwargs: Any): ...
    def restore_with_http_info(self, repository: Any, archived_node_ids: Any, **kwargs: Any): ...
    def search(self, repository: Any, pattern: Any, **kwargs: Any): ...
    def search_with_http_info(self, repository: Any, pattern: Any, **kwargs: Any): ...
    def search_0(self, repository: Any, pattern: Any, person: Any, **kwargs: Any): ...
    def search_0_with_http_info(self, repository: Any, pattern: Any, person: Any, **kwargs: Any): ...
