from edu_sharing_client.api_client import ApiClient as ApiClient
from typing import Any, Optional

class AUTHENTICATIONV1Api:
    api_client: Any = ...
    def __init__(self, api_client: Optional[Any] = ...) -> None: ...
    def has_access_to_scope(self, scope: Any, **kwargs: Any): ...
    def has_access_to_scope_with_http_info(self, scope: Any, **kwargs: Any): ...
    def login(self, **kwargs: Any): ...
    def login_with_http_info(self, **kwargs: Any): ...
    def login_to_scope(self, body: Any, **kwargs: Any): ...
    def login_to_scope_with_http_info(self, body: Any, **kwargs: Any): ...
    def logout(self, **kwargs: Any): ...
    def logout_with_http_info(self, **kwargs: Any): ...
