from edu_sharing_client.api_client import ApiClient as ApiClient
from typing import Any, Optional

class BULKV1Api:
    api_client: Any = ...
    def __init__(self, api_client: Optional[Any] = ...) -> None: ...
    def find(self, body: Any, **kwargs: Any): ...
    def find_with_http_info(self, body: Any, **kwargs: Any): ...
    def sync(self, body: Any, match: Any, type: Any, group: Any, **kwargs: Any): ...
    def sync_with_http_info(self, body: Any, match: Any, type: Any, group: Any, **kwargs: Any): ...
