from edu_sharing_client.api_client import ApiClient as ApiClient
from typing import Any, Optional

class CLIENTUTILSV1Api:
    api_client: Any = ...
    def __init__(self, api_client: Optional[Any] = ...) -> None: ...
    def get_website_information(self, **kwargs: Any): ...
    def get_website_information_with_http_info(self, **kwargs: Any): ...
