from edu_sharing_client.api_client import ApiClient as ApiClient
from typing import Any, Optional

class COMMENTV1Api:
    api_client: Any = ...
    def __init__(self, api_client: Optional[Any] = ...) -> None: ...
    def add_comment(self, body: Any, repository: Any, node: Any, **kwargs: Any): ...
    def add_comment_with_http_info(self, body: Any, repository: Any, node: Any, **kwargs: Any): ...
    def delete_comment(self, repository: Any, comment: Any, **kwargs: Any): ...
    def delete_comment_with_http_info(self, repository: Any, comment: Any, **kwargs: Any): ...
    def edit_comment(self, body: Any, repository: Any, comment: Any, **kwargs: Any): ...
    def edit_comment_with_http_info(self, body: Any, repository: Any, comment: Any, **kwargs: Any): ...
    def get_comments(self, repository: Any, node: Any, **kwargs: Any): ...
    def get_comments_with_http_info(self, repository: Any, node: Any, **kwargs: Any): ...
