from edu_sharing_client.api_client import ApiClient as ApiClient
from typing import Any, Optional

class CONFIGV1Api:
    api_client: Any = ...
    def __init__(self, api_client: Optional[Any] = ...) -> None: ...
    def get_config(self, **kwargs: Any): ...
    def get_config_with_http_info(self, **kwargs: Any): ...
    def get_dynamic_value(self, key: Any, **kwargs: Any): ...
    def get_dynamic_value_with_http_info(self, key: Any, **kwargs: Any): ...
    def get_language(self, **kwargs: Any): ...
    def get_language_with_http_info(self, **kwargs: Any): ...
    def get_language_defaults(self, **kwargs: Any): ...
    def get_language_defaults_with_http_info(self, **kwargs: Any): ...
    def get_variables(self, **kwargs: Any): ...
    def get_variables_with_http_info(self, **kwargs: Any): ...
    def set_dynamic_value(self, body: Any, public: Any, key: Any, **kwargs: Any): ...
    def set_dynamic_value_with_http_info(self, body: Any, public: Any, key: Any, **kwargs: Any): ...
