from edu_sharing_client.api_client import ApiClient as ApiClient
from typing import Any, Optional

class CONNECTORV1Api:
    api_client: Any = ...
    def __init__(self, api_client: Optional[Any] = ...) -> None: ...
    def list_connectors(self, repository: Any, **kwargs: Any): ...
    def list_connectors_with_http_info(self, repository: Any, **kwargs: Any): ...
