from edu_sharing_client.api_client import ApiClient as ApiClient
from typing import Any, Optional

class IAMV1Api:
    api_client: Any = ...
    def __init__(self, api_client: Optional[Any] = ...) -> None: ...
    def add_membership(self, repository: Any, group: Any, member: Any, **kwargs: Any): ...
    def add_membership_with_http_info(self, repository: Any, group: Any, member: Any, **kwargs: Any): ...
    def add_node_list(self, repository: Any, person: Any, list: Any, node: Any, **kwargs: Any): ...
    def add_node_list_with_http_info(self, repository: Any, person: Any, list: Any, node: Any, **kwargs: Any): ...
    def change_group_profile(self, body: Any, repository: Any, group: Any, **kwargs: Any): ...
    def change_group_profile_with_http_info(self, body: Any, repository: Any, group: Any, **kwargs: Any): ...
    def change_user_avatar(self, avatar: Any, repository: Any, person: Any, **kwargs: Any): ...
    def change_user_avatar_with_http_info(self, avatar: Any, repository: Any, person: Any, **kwargs: Any): ...
    def change_user_password(self, body: Any, repository: Any, person: Any, **kwargs: Any): ...
    def change_user_password_with_http_info(self, body: Any, repository: Any, person: Any, **kwargs: Any): ...
    def change_user_profile(self, body: Any, repository: Any, person: Any, **kwargs: Any): ...
    def change_user_profile_with_http_info(self, body: Any, repository: Any, person: Any, **kwargs: Any): ...
    def create_group(self, body: Any, repository: Any, group: Any, **kwargs: Any): ...
    def create_group_with_http_info(self, body: Any, repository: Any, group: Any, **kwargs: Any): ...
    def create_user(self, body: Any, repository: Any, person: Any, **kwargs: Any): ...
    def create_user_with_http_info(self, body: Any, repository: Any, person: Any, **kwargs: Any): ...
    def delete_group(self, repository: Any, group: Any, **kwargs: Any): ...
    def delete_group_with_http_info(self, repository: Any, group: Any, **kwargs: Any): ...
    def delete_membership(self, repository: Any, group: Any, member: Any, **kwargs: Any): ...
    def delete_membership_with_http_info(self, repository: Any, group: Any, member: Any, **kwargs: Any): ...
    def get_group(self, repository: Any, group: Any, **kwargs: Any): ...
    def get_group_with_http_info(self, repository: Any, group: Any, **kwargs: Any): ...
    def get_membership(self, repository: Any, group: Any, **kwargs: Any): ...
    def get_membership_with_http_info(self, repository: Any, group: Any, **kwargs: Any): ...
    def get_node_list(self, repository: Any, person: Any, list: Any, **kwargs: Any): ...
    def get_node_list_with_http_info(self, repository: Any, person: Any, list: Any, **kwargs: Any): ...
    def get_preferences(self, repository: Any, person: Any, **kwargs: Any): ...
    def get_preferences_with_http_info(self, repository: Any, person: Any, **kwargs: Any): ...
    def get_recently_invited(self, repository: Any, **kwargs: Any): ...
    def get_recently_invited_with_http_info(self, repository: Any, **kwargs: Any): ...
    def get_subgroup_by_type(self, repository: Any, group: Any, type: Any, **kwargs: Any): ...
    def get_subgroup_by_type_with_http_info(self, repository: Any, group: Any, type: Any, **kwargs: Any): ...
    def get_user(self, repository: Any, person: Any, **kwargs: Any): ...
    def get_user_with_http_info(self, repository: Any, person: Any, **kwargs: Any): ...
    def get_user_groups(self, repository: Any, person: Any, **kwargs: Any): ...
    def get_user_groups_with_http_info(self, repository: Any, person: Any, **kwargs: Any): ...
    def remove_node_list(self, repository: Any, person: Any, list: Any, node: Any, **kwargs: Any): ...
    def remove_node_list_with_http_info(self, repository: Any, person: Any, list: Any, node: Any, **kwargs: Any): ...
    def remove_user_avatar(self, repository: Any, person: Any, **kwargs: Any): ...
    def remove_user_avatar_with_http_info(self, repository: Any, person: Any, **kwargs: Any): ...
    def search_authorities(self, repository: Any, pattern: Any, **kwargs: Any): ...
    def search_authorities_with_http_info(self, repository: Any, pattern: Any, **kwargs: Any): ...
    def search_groups(self, repository: Any, pattern: Any, **kwargs: Any): ...
    def search_groups_with_http_info(self, repository: Any, pattern: Any, **kwargs: Any): ...
    def search_user(self, repository: Any, pattern: Any, **kwargs: Any): ...
    def search_user_with_http_info(self, repository: Any, pattern: Any, **kwargs: Any): ...
    def set_preferences(self, body: Any, repository: Any, person: Any, **kwargs: Any): ...
    def set_preferences_with_http_info(self, body: Any, repository: Any, person: Any, **kwargs: Any): ...
    def update_user_status(self, repository: Any, person: Any, status: Any, notify: Any, **kwargs: Any): ...
    def update_user_status_with_http_info(self, repository: Any, person: Any, status: Any, notify: Any, **kwargs: Any): ...
