from edu_sharing_client.api_client import ApiClient as ApiClient
from typing import Any, Optional

class MDSV1Api:
    api_client: Any = ...
    def __init__(self, api_client: Optional[Any] = ...) -> None: ...
    def get_metadata_set_v2(self, repository: Any, metadataset: Any, **kwargs: Any): ...
    def get_metadata_set_v2_with_http_info(self, repository: Any, metadataset: Any, **kwargs: Any): ...
    def get_metadata_sets_v2(self, repository: Any, **kwargs: Any): ...
    def get_metadata_sets_v2_with_http_info(self, repository: Any, **kwargs: Any): ...
    def get_values_v2(self, repository: Any, metadataset: Any, **kwargs: Any): ...
    def get_values_v2_with_http_info(self, repository: Any, metadataset: Any, **kwargs: Any): ...
