from edu_sharing_client.api_client import ApiClient as ApiClient
from typing import Any, Optional

class MEDIACENTERV1Api:
    api_client: Any = ...
    def __init__(self, api_client: Optional[Any] = ...) -> None: ...
    def add_mediacenter_group(self, repository: Any, mediacenter: Any, group: Any, **kwargs: Any): ...
    def add_mediacenter_group_with_http_info(self, repository: Any, mediacenter: Any, group: Any, **kwargs: Any): ...
    def create_mediacenter(self, repository: Any, mediacenter: Any, **kwargs: Any): ...
    def create_mediacenter_with_http_info(self, repository: Any, mediacenter: Any, **kwargs: Any): ...
    def delete_mediacenter(self, repository: Any, mediacenter: Any, **kwargs: Any): ...
    def delete_mediacenter_with_http_info(self, repository: Any, mediacenter: Any, **kwargs: Any): ...
    def edit_mediacenter(self, repository: Any, mediacenter: Any, **kwargs: Any): ...
    def edit_mediacenter_with_http_info(self, repository: Any, mediacenter: Any, **kwargs: Any): ...
    def get_mediacenter_groups(self, repository: Any, mediacenter: Any, **kwargs: Any): ...
    def get_mediacenter_groups_with_http_info(self, repository: Any, mediacenter: Any, **kwargs: Any): ...
    def get_mediacenter_licensed_nodes(self, repository: Any, mediacenter: Any, searchword: Any, **kwargs: Any): ...
    def get_mediacenter_licensed_nodes_with_http_info(self, repository: Any, mediacenter: Any, searchword: Any, **kwargs: Any): ...
    def get_mediacenters(self, repository: Any, **kwargs: Any): ...
    def get_mediacenters_with_http_info(self, repository: Any, **kwargs: Any): ...
    def import_mc_org_connections(self, mc_orgs: Any, **kwargs: Any): ...
    def import_mc_org_connections_with_http_info(self, mc_orgs: Any, **kwargs: Any): ...
    def import_mediacenters(self, mediacenters: Any, **kwargs: Any): ...
    def import_mediacenters_with_http_info(self, mediacenters: Any, **kwargs: Any): ...
    def import_organisations(self, organisations: Any, **kwargs: Any): ...
    def import_organisations_with_http_info(self, organisations: Any, **kwargs: Any): ...
    def remove_mediacenter_group(self, repository: Any, mediacenter: Any, group: Any, **kwargs: Any): ...
    def remove_mediacenter_group_with_http_info(self, repository: Any, mediacenter: Any, group: Any, **kwargs: Any): ...
