from edu_sharing_client.api_client import ApiClient as ApiClient
from typing import Any, Optional

class NETWORKV1Api:
    api_client: Any = ...
    def __init__(self, api_client: Optional[Any] = ...) -> None: ...
    def add_service(self, **kwargs: Any): ...
    def add_service_with_http_info(self, **kwargs: Any): ...
    def get_repositories(self, **kwargs: Any): ...
    def get_repositories_with_http_info(self, **kwargs: Any): ...
    def get_service(self, **kwargs: Any): ...
    def get_service_with_http_info(self, **kwargs: Any): ...
    def get_services(self, **kwargs: Any): ...
    def get_services_with_http_info(self, **kwargs: Any): ...
    def update_service(self, id: Any, **kwargs: Any): ...
    def update_service_with_http_info(self, id: Any, **kwargs: Any): ...
