from edu_sharing_client.api_client import ApiClient as ApiClient
from typing import Any, Optional

class NODEV1Api:
    api_client: Any = ...
    def __init__(self, api_client: Optional[Any] = ...) -> None: ...
    def add_aspects(self, body: Any, repository: Any, node: Any, **kwargs: Any): ...
    def add_aspects_with_http_info(self, body: Any, repository: Any, node: Any, **kwargs: Any): ...
    def add_workflow_history(self, body: Any, repository: Any, node: Any, **kwargs: Any): ...
    def add_workflow_history_with_http_info(self, body: Any, repository: Any, node: Any, **kwargs: Any): ...
    def change_content(self, mimetype: Any, repository: Any, node: Any, **kwargs: Any): ...
    def change_content_with_http_info(self, mimetype: Any, repository: Any, node: Any, **kwargs: Any): ...
    def change_content_as_text(self, repository: Any, node: Any, mimetype: Any, **kwargs: Any): ...
    def change_content_as_text_with_http_info(self, repository: Any, node: Any, mimetype: Any, **kwargs: Any): ...
    def change_metadata(self, body: Any, repository: Any, node: Any, **kwargs: Any): ...
    def change_metadata_with_http_info(self, body: Any, repository: Any, node: Any, **kwargs: Any): ...
    def change_metadata_with_versioning(self, body: Any, version_comment: Any, repository: Any, node: Any, **kwargs: Any): ...
    def change_metadata_with_versioning_with_http_info(self, body: Any, version_comment: Any, repository: Any, node: Any, **kwargs: Any): ...
    def change_preview(self, mimetype: Any, repository: Any, node: Any, **kwargs: Any): ...
    def change_preview_with_http_info(self, mimetype: Any, repository: Any, node: Any, **kwargs: Any): ...
    def change_template_metadata(self, body: Any, enable: Any, repository: Any, node: Any, **kwargs: Any): ...
    def change_template_metadata_with_http_info(self, body: Any, enable: Any, repository: Any, node: Any, **kwargs: Any): ...
    def create_child(self, body: Any, type: Any, repository: Any, node: Any, **kwargs: Any): ...
    def create_child_with_http_info(self, body: Any, type: Any, repository: Any, node: Any, **kwargs: Any): ...
    def create_child_by_copying(self, repository: Any, node: Any, source: Any, with_children: Any, **kwargs: Any): ...
    def create_child_by_copying_with_http_info(self, repository: Any, node: Any, source: Any, with_children: Any, **kwargs: Any): ...
    def create_child_by_moving(self, repository: Any, node: Any, source: Any, **kwargs: Any): ...
    def create_child_by_moving_with_http_info(self, repository: Any, node: Any, source: Any, **kwargs: Any): ...
    def create_fork_of_node(self, repository: Any, node: Any, source: Any, with_children: Any, **kwargs: Any): ...
    def create_fork_of_node_with_http_info(self, repository: Any, node: Any, source: Any, with_children: Any, **kwargs: Any): ...
    def create_share(self, repository: Any, node: Any, **kwargs: Any): ...
    def create_share_with_http_info(self, repository: Any, node: Any, **kwargs: Any): ...
    def delete(self, repository: Any, node: Any, **kwargs: Any): ...
    def delete_with_http_info(self, repository: Any, node: Any, **kwargs: Any): ...
    def delete_preview(self, repository: Any, node: Any, **kwargs: Any): ...
    def delete_preview_with_http_info(self, repository: Any, node: Any, **kwargs: Any): ...
    def get_assocs(self, repository: Any, node: Any, direction: Any, **kwargs: Any): ...
    def get_assocs_with_http_info(self, repository: Any, node: Any, direction: Any, **kwargs: Any): ...
    def get_children(self, repository: Any, node: Any, **kwargs: Any): ...
    def get_children_with_http_info(self, repository: Any, node: Any, **kwargs: Any): ...
    def get_metadata(self, repository: Any, node: Any, **kwargs: Any): ...
    def get_metadata_with_http_info(self, repository: Any, node: Any, **kwargs: Any): ...
    def get_nodes(self, repository: Any, query: Any, **kwargs: Any): ...
    def get_nodes_with_http_info(self, repository: Any, query: Any, **kwargs: Any): ...
    def get_notify_list(self, repository: Any, node: Any, **kwargs: Any): ...
    def get_notify_list_with_http_info(self, repository: Any, node: Any, **kwargs: Any): ...
    def get_parents(self, repository: Any, node: Any, **kwargs: Any): ...
    def get_parents_with_http_info(self, repository: Any, node: Any, **kwargs: Any): ...
    def get_permission(self, repository: Any, node: Any, **kwargs: Any): ...
    def get_permission_with_http_info(self, repository: Any, node: Any, **kwargs: Any): ...
    def get_shares(self, repository: Any, node: Any, **kwargs: Any): ...
    def get_shares_with_http_info(self, repository: Any, node: Any, **kwargs: Any): ...
    def get_template_metadata(self, repository: Any, node: Any, **kwargs: Any): ...
    def get_template_metadata_with_http_info(self, repository: Any, node: Any, **kwargs: Any): ...
    def get_text_content(self, repository: Any, node: Any, **kwargs: Any): ...
    def get_text_content_with_http_info(self, repository: Any, node: Any, **kwargs: Any): ...
    def get_version_metadata(self, repository: Any, node: Any, major: Any, minor: Any, **kwargs: Any): ...
    def get_version_metadata_with_http_info(self, repository: Any, node: Any, major: Any, minor: Any, **kwargs: Any): ...
    def get_versions(self, repository: Any, node: Any, **kwargs: Any): ...
    def get_versions_with_http_info(self, repository: Any, node: Any, **kwargs: Any): ...
    def get_workflow_history(self, repository: Any, node: Any, **kwargs: Any): ...
    def get_workflow_history_with_http_info(self, repository: Any, node: Any, **kwargs: Any): ...
    def has_permission(self, repository: Any, node: Any, user: Any, **kwargs: Any): ...
    def has_permission_with_http_info(self, repository: Any, node: Any, user: Any, **kwargs: Any): ...
    def import_node(self, repository: Any, node: Any, parent: Any, **kwargs: Any): ...
    def import_node_with_http_info(self, repository: Any, node: Any, parent: Any, **kwargs: Any): ...
    def islocked(self, repository: Any, node: Any, **kwargs: Any): ...
    def islocked_with_http_info(self, repository: Any, node: Any, **kwargs: Any): ...
    def prepare_usage(self, repository: Any, node: Any, **kwargs: Any): ...
    def prepare_usage_with_http_info(self, repository: Any, node: Any, **kwargs: Any): ...
    def remove_share(self, repository: Any, node: Any, share_id: Any, **kwargs: Any): ...
    def remove_share_with_http_info(self, repository: Any, node: Any, share_id: Any, **kwargs: Any): ...
    def report_node(self, repository: Any, node: Any, reason: Any, user_email: Any, **kwargs: Any): ...
    def report_node_with_http_info(self, repository: Any, node: Any, reason: Any, user_email: Any, **kwargs: Any): ...
    def revert_version(self, repository: Any, node: Any, major: Any, minor: Any, **kwargs: Any): ...
    def revert_version_with_http_info(self, repository: Any, node: Any, major: Any, minor: Any, **kwargs: Any): ...
    def set_owner(self, repository: Any, node: Any, **kwargs: Any): ...
    def set_owner_with_http_info(self, repository: Any, node: Any, **kwargs: Any): ...
    def set_permission(self, body: Any, send_mail: Any, send_copy: Any, repository: Any, node: Any, **kwargs: Any): ...
    def set_permission_with_http_info(self, body: Any, send_mail: Any, send_copy: Any, repository: Any, node: Any, **kwargs: Any): ...
    def set_property(self, repository: Any, node: Any, _property: Any, **kwargs: Any): ...
    def set_property_with_http_info(self, repository: Any, node: Any, _property: Any, **kwargs: Any): ...
    def store_x_api_data(self, body: Any, repository: Any, node: Any, **kwargs: Any): ...
    def store_x_api_data_with_http_info(self, body: Any, repository: Any, node: Any, **kwargs: Any): ...
    def unlock(self, repository: Any, node: Any, **kwargs: Any): ...
    def unlock_with_http_info(self, repository: Any, node: Any, **kwargs: Any): ...
    def update_share(self, repository: Any, node: Any, share_id: Any, **kwargs: Any): ...
    def update_share_with_http_info(self, repository: Any, node: Any, share_id: Any, **kwargs: Any): ...
