from edu_sharing_client.api_client import ApiClient as ApiClient
from typing import Any, Optional

class ORGANIZATIONV1Api:
    api_client: Any = ...
    def __init__(self, api_client: Optional[Any] = ...) -> None: ...
    def create_organizations(self, repository: Any, organization: Any, **kwargs: Any): ...
    def create_organizations_with_http_info(self, repository: Any, organization: Any, **kwargs: Any): ...
    def delete_organizations(self, repository: Any, organization: Any, **kwargs: Any): ...
    def delete_organizations_with_http_info(self, repository: Any, organization: Any, **kwargs: Any): ...
    def get_organization(self, repository: Any, organization: Any, **kwargs: Any): ...
    def get_organization_with_http_info(self, repository: Any, organization: Any, **kwargs: Any): ...
    def get_organizations(self, repository: Any, **kwargs: Any): ...
    def get_organizations_with_http_info(self, repository: Any, **kwargs: Any): ...
    def remove_from_organization(self, repository: Any, organization: Any, member: Any, **kwargs: Any): ...
    def remove_from_organization_with_http_info(self, repository: Any, organization: Any, member: Any, **kwargs: Any): ...
