from edu_sharing_client.api_client import ApiClient as ApiClient
from typing import Any, Optional

class REGISTERV1Api:
    api_client: Any = ...
    def __init__(self, api_client: Optional[Any] = ...) -> None: ...
    def activate(self, key: Any, **kwargs: Any): ...
    def activate_with_http_info(self, key: Any, **kwargs: Any): ...
    def mail_exists(self, mail: Any, **kwargs: Any): ...
    def mail_exists_with_http_info(self, mail: Any, **kwargs: Any): ...
    def recover_password(self, mail: Any, **kwargs: Any): ...
    def recover_password_with_http_info(self, mail: Any, **kwargs: Any): ...
    def register(self, **kwargs: Any): ...
    def register_with_http_info(self, **kwargs: Any): ...
    def resend_mail(self, mail: Any, **kwargs: Any): ...
    def resend_mail_with_http_info(self, mail: Any, **kwargs: Any): ...
    def reset_password(self, key: Any, password: Any, **kwargs: Any): ...
    def reset_password_with_http_info(self, key: Any, password: Any, **kwargs: Any): ...
