from edu_sharing_client.api_client import ApiClient as ApiClient
from typing import Any, Optional

class RENDERINGV1Api:
    api_client: Any = ...
    def __init__(self, api_client: Optional[Any] = ...) -> None: ...
    def get_details_snippet(self, repository: Any, node: Any, **kwargs: Any): ...
    def get_details_snippet_with_http_info(self, repository: Any, node: Any, **kwargs: Any): ...
    def get_details_snippet_with_parameters(self, repository: Any, node: Any, **kwargs: Any): ...
    def get_details_snippet_with_parameters_with_http_info(self, repository: Any, node: Any, **kwargs: Any): ...
