from edu_sharing_client.api_client import ApiClient as ApiClient
from typing import Any, Optional

class SEARCHV1Api:
    api_client: Any = ...
    def __init__(self, api_client: Optional[Any] = ...) -> None: ...
    def get_relevant_nodes(self, repository: Any, **kwargs: Any): ...
    def get_relevant_nodes_with_http_info(self, repository: Any, **kwargs: Any): ...
    def load_save_search(self, node_id: Any, **kwargs: Any): ...
    def load_save_search_with_http_info(self, node_id: Any, **kwargs: Any): ...
    def save_search(self, body: Any, name: Any, repository: Any, metadataset: Any, query: Any, **kwargs: Any): ...
    def save_search_with_http_info(self, body: Any, name: Any, repository: Any, metadataset: Any, query: Any, **kwargs: Any): ...
    def search_by_property(self, repository: Any, **kwargs: Any): ...
    def search_by_property_with_http_info(self, repository: Any, **kwargs: Any): ...
    def search_fingerprint(self, repository: Any, nodeid: Any, **kwargs: Any): ...
    def search_fingerprint_with_http_info(self, repository: Any, nodeid: Any, **kwargs: Any): ...
    def search_v2(self, body: Any, repository: Any, metadataset: Any, query: Any, **kwargs: Any): ...
    def search_v2_with_http_info(self, body: Any, repository: Any, metadataset: Any, query: Any, **kwargs: Any): ...
