from edu_sharing_client.api_client import ApiClient as ApiClient
from typing import Any, Optional

class SHARINGV1Api:
    api_client: Any = ...
    def __init__(self, api_client: Optional[Any] = ...) -> None: ...
    def get_children(self, repository: Any, node: Any, share: Any, **kwargs: Any): ...
    def get_children_with_http_info(self, repository: Any, node: Any, share: Any, **kwargs: Any): ...
    def get_info(self, repository: Any, node: Any, share: Any, **kwargs: Any): ...
    def get_info_with_http_info(self, repository: Any, node: Any, share: Any, **kwargs: Any): ...
