from edu_sharing_client.api_client import ApiClient as ApiClient
from typing import Any, Optional

class STATISTICV1Api:
    api_client: Any = ...
    def __init__(self, api_client: Optional[Any] = ...) -> None: ...
    def get(self, body: Any, context: Any, **kwargs: Any): ...
    def get_with_http_info(self, body: Any, context: Any, **kwargs: Any): ...
    def get_global_statistics(self, **kwargs: Any): ...
    def get_global_statistics_with_http_info(self, **kwargs: Any): ...
    def get_statistics_node(self, grouping: Any, date_from: Any, date_to: Any, **kwargs: Any): ...
    def get_statistics_node_with_http_info(self, grouping: Any, date_from: Any, date_to: Any, **kwargs: Any): ...
    def get_statistics_user(self, grouping: Any, date_from: Any, date_to: Any, **kwargs: Any): ...
    def get_statistics_user_with_http_info(self, grouping: Any, date_from: Any, date_to: Any, **kwargs: Any): ...
