from edu_sharing_client.api_client import ApiClient as ApiClient
from typing import Any, Optional

class STREAMV1Api:
    api_client: Any = ...
    def __init__(self, api_client: Optional[Any] = ...) -> None: ...
    def add_entry(self, body: Any, repository: Any, **kwargs: Any): ...
    def add_entry_with_http_info(self, body: Any, repository: Any, **kwargs: Any): ...
    def can_access(self, repository: Any, node: Any, **kwargs: Any): ...
    def can_access_with_http_info(self, repository: Any, node: Any, **kwargs: Any): ...
    def delete_entry(self, repository: Any, entry: Any, **kwargs: Any): ...
    def delete_entry_with_http_info(self, repository: Any, entry: Any, **kwargs: Any): ...
    def get_property_values(self, repository: Any, _property: Any, **kwargs: Any): ...
    def get_property_values_with_http_info(self, repository: Any, _property: Any, **kwargs: Any): ...
    def search(self, repository: Any, **kwargs: Any): ...
    def search_with_http_info(self, repository: Any, **kwargs: Any): ...
    def update_entry(self, repository: Any, entry: Any, authority: Any, status: Any, **kwargs: Any): ...
    def update_entry_with_http_info(self, repository: Any, entry: Any, authority: Any, status: Any, **kwargs: Any): ...
