from edu_sharing_client.api_client import ApiClient as ApiClient
from typing import Any, Optional

class TOOLV1Api:
    api_client: Any = ...
    def __init__(self, api_client: Optional[Any] = ...) -> None: ...
    def create_tool_defintition(self, body: Any, repository: Any, **kwargs: Any): ...
    def create_tool_defintition_with_http_info(self, body: Any, repository: Any, **kwargs: Any): ...
    def create_tool_instance(self, body: Any, repository: Any, tool_definition: Any, **kwargs: Any): ...
    def create_tool_instance_with_http_info(self, body: Any, repository: Any, tool_definition: Any, **kwargs: Any): ...
    def create_tool_object(self, body: Any, repository: Any, toolinstance: Any, **kwargs: Any): ...
    def create_tool_object_with_http_info(self, body: Any, repository: Any, toolinstance: Any, **kwargs: Any): ...
    def get_all_tool_definitions(self, repository: Any, **kwargs: Any): ...
    def get_all_tool_definitions_with_http_info(self, repository: Any, **kwargs: Any): ...
    def get_instance(self, repository: Any, nodeid: Any, **kwargs: Any): ...
    def get_instance_with_http_info(self, repository: Any, nodeid: Any, **kwargs: Any): ...
    def get_instances(self, repository: Any, tool_definition: Any, **kwargs: Any): ...
    def get_instances_with_http_info(self, repository: Any, tool_definition: Any, **kwargs: Any): ...
