from edu_sharing_client.api_client import ApiClient as ApiClient
from typing import Any, Optional

class TRACKINGV1Api:
    api_client: Any = ...
    def __init__(self, api_client: Optional[Any] = ...) -> None: ...
    def track_event(self, repository: Any, event: Any, **kwargs: Any): ...
    def track_event_with_http_info(self, repository: Any, event: Any, **kwargs: Any): ...
