from edu_sharing_client.api_client import ApiClient as ApiClient
from typing import Any, Optional

class USAGEV1Api:
    api_client: Any = ...
    def __init__(self, api_client: Optional[Any] = ...) -> None: ...
    def delete_usage(self, node_id: Any, usage_id: Any, **kwargs: Any): ...
    def delete_usage_with_http_info(self, node_id: Any, usage_id: Any, **kwargs: Any): ...
    def get_usages(self, repository_id: Any, node_id: Any, **kwargs: Any): ...
    def get_usages_with_http_info(self, repository_id: Any, node_id: Any, **kwargs: Any): ...
    def get_usages_0(self, app_id: Any, **kwargs: Any): ...
    def get_usages_0_with_http_info(self, app_id: Any, **kwargs: Any): ...
    def get_usages_by_course(self, app_id: Any, course_id: Any, **kwargs: Any): ...
    def get_usages_by_course_with_http_info(self, app_id: Any, course_id: Any, **kwargs: Any): ...
    def get_usages_by_node(self, node_id: Any, **kwargs: Any): ...
    def get_usages_by_node_with_http_info(self, node_id: Any, **kwargs: Any): ...
    def get_usages_by_node_collections(self, node_id: Any, **kwargs: Any): ...
    def get_usages_by_node_collections_with_http_info(self, node_id: Any, **kwargs: Any): ...
