#!/bin/bash -e

# not the best solution, but we need to make sure elastic is running first before re-creating the index
until curl http://elasticsearch:9200/_cluster/health?wait_for_status=yellow; do echo .; sleep 5; done;
# delete is not so good if incremental transfer is enabled!
# curl --header 'Content-Type: application/json' --request DELETE http://elasticsearch:9200/search_idx
curl --header 'Content-Type: application/json' --request PUT http://elasticsearch:9200/search_idx --data-binary '@/usr/share/logstash/templates/elastic-index.json'
echo 'Added/Recreated Elasticsearch Index File'
# Map environment variables to entries in logstash.yml.
# Note that this will mutate logstash.yml in place if any such settings are found.
# This may be undesirable, especially if logstash.yml is bind-mounted from the
# host system.
env2yaml /usr/share/logstash/config/logstash.yml

export LS_JAVA_OPTS="-Dls.cgroup.cpuacct.path.override=/ -Dls.cgroup.cpu.path.override=/ $LS_JAVA_OPTS"

if [[ -z $1 ]] || [[ ${1:0:1} == '-' ]] ; then
  exec logstash "$@"
else
  exec "$@"
fi
