from scrapy.exceptions import UsageError as UsageError
from scrapy.utils.conf import arglist_to_dict as arglist_to_dict, feed_process_params_from_cli as feed_process_params_from_cli
from typing import Any

class ScrapyCommand:
    requires_project: bool = ...
    crawler_process: Any = ...
    default_settings: Any = ...
    exitcode: int = ...
    settings: Any = ...
    def __init__(self) -> None: ...
    def set_crawler(self, crawler: Any) -> None: ...
    def syntax(self): ...
    def short_desc(self): ...
    def long_desc(self): ...
    def help(self): ...
    def add_options(self, parser: Any) -> None: ...
    def process_options(self, args: Any, opts: Any) -> None: ...
    def run(self, args: Any, opts: Any) -> None: ...

class BaseRunSpiderCommand(ScrapyCommand):
    def add_options(self, parser: Any) -> None: ...
    def process_options(self, args: Any, opts: Any) -> None: ...
