import scrapy
from scrapy.commands import ScrapyCommand as ScrapyCommand
from scrapy.linkextractors import LinkExtractor as LinkExtractor
from typing import Any

class Command(ScrapyCommand):
    default_settings: Any = ...
    def short_desc(self): ...
    def run(self, args: Any, opts: Any) -> None: ...

class _BenchServer:
    proc: Any = ...
    def __enter__(self) -> None: ...
    def __exit__(self, exc_type: Any, exc_value: Any, traceback: Any) -> None: ...

class _BenchSpider(scrapy.Spider):
    name: str = ...
    total: int = ...
    show: int = ...
    baseurl: str = ...
    link_extractor: Any = ...
    def start_requests(self): ...
    def parse(self, response: Any) -> None: ...
