from scrapy.commands import ScrapyCommand as ScrapyCommand
from scrapy.exceptions import UsageError as UsageError
from scrapy.utils.template import render_templatefile as render_templatefile, string_camelcase as string_camelcase
from typing import Any

def sanitize_module_name(module_name: Any): ...

class Command(ScrapyCommand):
    requires_project: bool = ...
    default_settings: Any = ...
    def syntax(self): ...
    def short_desc(self): ...
    def add_options(self, parser: Any) -> None: ...
    exitcode: Any = ...
    def run(self, args: Any, opts: Any) -> None: ...
    @property
    def templates_dir(self): ...
