from scrapy.commands import BaseRunSpiderCommand as BaseRunSpiderCommand
from scrapy.exceptions import UsageError as UsageError
from scrapy.utils.spider import iter_spider_classes as iter_spider_classes
from typing import Any

class Command(BaseRunSpiderCommand):
    requires_project: bool = ...
    default_settings: Any = ...
    def syntax(self): ...
    def short_desc(self): ...
    def long_desc(self): ...
    exitcode: int = ...
    def run(self, args: Any, opts: Any) -> None: ...
