from scrapy.commands import ScrapyCommand as ScrapyCommand
from scrapy.settings import BaseSettings as BaseSettings
from typing import Any

class Command(ScrapyCommand):
    requires_project: bool = ...
    default_settings: Any = ...
    def syntax(self): ...
    def short_desc(self): ...
    def add_options(self, parser: Any) -> None: ...
    def run(self, args: Any, opts: Any) -> None: ...
