from scrapy.commands import ScrapyCommand as ScrapyCommand
from scrapy.utils.versions import scrapy_components_versions as scrapy_components_versions
from typing import Any

class Command(ScrapyCommand):
    default_settings: Any = ...
    def syntax(self): ...
    def short_desc(self): ...
    def add_options(self, parser: Any) -> None: ...
    def run(self, args: Any, opts: Any) -> None: ...
