from scrapy.exceptions import ScrapyDeprecationWarning as ScrapyDeprecationWarning, UsageError as UsageError
from scrapy.settings import BaseSettings as BaseSettings
from scrapy.utils.deprecate import update_classpath as update_classpath
from scrapy.utils.python import without_none_values as without_none_values
from typing import Any, Optional

def build_component_list(compdict: Any, custom: Optional[Any] = ..., convert: Any = ...): ...
def arglist_to_dict(arglist: Any): ...
def closest_scrapy_cfg(path: str = ..., prevpath: Optional[Any] = ...): ...
def init_env(project: str = ..., set_syspath: bool = ...) -> None: ...
def get_config(use_closest: bool = ...): ...
def get_sources(use_closest: bool = ...): ...
def feed_complete_default_values_from_settings(feed: Any, settings: Any): ...
def feed_process_params_from_cli(settings: Any, output: Any, output_format: Optional[Any] = ..., overwrite_output: Optional[Any] = ...): ...
