from scrapy.exceptions import ScrapyDeprecationWarning as ScrapyDeprecationWarning
from typing import Any, Optional

def deprecated(use_instead: Optional[Any] = ...): ...
def defers(func: Any): ...
def inthread(func: Any): ...
