from time import time as time
from typing import Any, Optional

def get_engine_status(engine: Any): ...
def format_engine_status(engine: Optional[Any] = ...): ...
def print_engine_status(engine: Any) -> None: ...
