from typing import Any

def ftp_makedirs_cwd(ftp: Any, path: Any, first_call: bool = ...) -> None: ...
def ftp_store_file(path: Any, file: Any, host: Any, port: Any, username: Any, password: Any, *, use_active_mode: bool = ..., overwrite: bool = ...) -> None: ...
