from scrapy.utils.decorators import deprecated as deprecated
from typing import Any

def read1(gzf: Any, size: int = ...): ...
def gunzip(data: Any): ...
def is_gzipped(response: Any): ...
def gzip_magic_number(response: Any): ...
