from scrapy.http import Response as Response, TextResponse as TextResponse
from scrapy.selector import Selector as Selector
from scrapy.utils.python import re_rsearch as re_rsearch, to_unicode as to_unicode
from typing import Any, Optional

logger: Any

def xmliter(obj: Any, nodename: Any) -> None: ...
def xmliter_lxml(obj: Any, nodename: Any, namespace: Optional[Any] = ..., prefix: str = ...) -> None: ...

class _StreamReader:
    def __init__(self, obj: Any) -> None: ...
    def read(self, n: int = ...): ...

def csviter(obj: Any, delimiter: Optional[Any] = ..., headers: Optional[Any] = ..., encoding: Optional[Any] = ..., quotechar: Optional[Any] = ...): ...
