from scrapy.utils.datatypes import LocalWeakReferencedCache as LocalWeakReferencedCache
from scrapy.utils.deprecate import ScrapyDeprecationWarning as ScrapyDeprecationWarning
from scrapy.utils.python import flatten as flatten, to_unicode as to_unicode
from typing import Any

def arg_to_iter(arg: Any): ...
def load_object(path: Any): ...
def walk_modules(path: Any): ...
def extract_regex(regex: Any, text: Any, encoding: str = ...): ...
def md5sum(file: Any): ...
def rel_has_nofollow(rel: Any): ...
def create_instance(objcls: Any, settings: Any, crawler: Any, *args: Any, **kwargs: Any): ...
def set_environ(**kwargs: Any) -> None: ...
def walk_callable(node: Any) -> None: ...
def is_generator_with_return_value(callable: Any): ...
def warn_on_generator_with_return_value(spider: Any, callable: Any) -> None: ...
