from scrapy.utils.misc import load_object as load_object
from typing import Any, Optional

def listen_tcp(portrange: Any, host: Any, factory: Any): ...

class CallLaterOnce:
    def __init__(self, func: Any, *a: Any, **kw: Any) -> None: ...
    def schedule(self, delay: int = ...) -> None: ...
    def cancel(self) -> None: ...
    def __call__(self): ...

def install_reactor(reactor_path: Any, event_loop_path: Optional[Any] = ...) -> None: ...
def verify_installed_reactor(reactor_path: Any) -> None: ...
def is_asyncio_reactor_installed(): ...
