from scrapy.utils.httpobj import urlparse_cached as urlparse_cached
from scrapy.utils.python import to_bytes as to_bytes, to_unicode as to_unicode
from typing import Any, Optional

def request_fingerprint(request: Any, include_headers: Optional[Any] = ..., keep_fragments: bool = ...): ...
def request_authenticate(request: Any, username: Any, password: Any) -> None: ...
def request_httprepr(request: Any): ...
def referer_str(request: Any): ...
