from scrapy.utils.python import to_bytes as to_bytes, to_unicode as to_unicode
from typing import Any

def get_base_url(response: Any): ...
def get_meta_refresh(response: Any, ignore_tags: Any = ...): ...
def response_status_message(status: Any): ...
def response_httprepr(response: Any): ...
def open_in_browser(response: Any, _openfunc: Any = ...): ...
