from pydispatch.dispatcher import Any
from scrapy.exceptions import StopDownload as StopDownload
from scrapy.utils.defer import maybeDeferred_coro as maybeDeferred_coro
from scrapy.utils.log import failure_to_exc_info as failure_to_exc_info

logger: Any

class _IgnoredException(Exception): ...

def send_catch_log(signal: Any = ..., sender: Any = ..., *arguments: Any, **named: Any): ...
def send_catch_log_deferred(signal: Any = ..., sender: Any = ..., *arguments: Any, **named: Any): ...
def disconnect_all(signal: Any = ..., sender: Any = ...) -> None: ...
