from typing import Any, Optional

class Sitemap:
    type: Any = ...
    def __init__(self, xmltext: Any) -> None: ...
    def __iter__(self) -> Any: ...

def sitemap_urls_from_robots(robots_text: Any, base_url: Optional[Any] = ...) -> None: ...
