from scrapy.utils.python import to_unicode as to_unicode
from typing import Any

SSL_OP_NO_TLSv1_3: Any

def ffi_buf_to_string(buf: Any): ...
def x509name_to_string(x509name: Any): ...
def get_temp_key_info(ssl_object: Any): ...
def get_openssl_version(): ...
