from typing import Any

NoneType: Any
live_refs: Any

class object_ref:
    def __new__(cls, *args: Any, **kwargs: Any): ...

def format_live_refs(ignore: Any = ...): ...
def print_live_refs(*a: Any, **kw: Any) -> None: ...
def get_oldest(class_name: Any): ...
def iter_all(class_name: Any): ...
