from w3lib.url import *
from scrapy.utils.python import to_unicode as to_unicode
from typing import Any, Optional

def url_is_from_any_domain(url: Any, domains: Any): ...
def url_is_from_spider(url: Any, spider: Any): ...
def url_has_any_extension(url: Any, extensions: Any): ...
def parse_url(url: Any, encoding: Optional[Any] = ...): ...
def escape_ajax(url: Any): ...
def add_http_if_no_scheme(url: Any): ...
def guess_scheme(url: Any): ...
def strip_url(url: Any, strip_credentials: bool = ..., strip_default_port: bool = ..., origin_only: bool = ..., strip_fragment: bool = ...): ...
