# coding: utf-8

"""
    edu-sharing Repository REST API

    The public restful API of the edu-sharing repository.

    The version of the OpenAPI document: 1.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from edu_sharing_client.api.toolv1_api import TOOLV1Api


class TestTOOLV1Api(unittest.TestCase):
    """TOOLV1Api unit test stubs"""

    def setUp(self) -> None:
        self.api = TOOLV1Api()

    def tearDown(self) -> None:
        pass

    def test_create_tool_defintition(self) -> None:
        """Test case for create_tool_defintition

        Create a new tool definition object.
        """
        pass

    def test_create_tool_instance(self) -> None:
        """Test case for create_tool_instance

        Create a new tool Instance object.
        """
        pass

    def test_create_tool_object(self) -> None:
        """Test case for create_tool_object

        Create a new tool object for a given tool instance.
        """
        pass

    def test_get_all_tool_definitions(self) -> None:
        """Test case for get_all_tool_definitions

        Get all ToolDefinitions.
        """
        pass

    def test_get_instance(self) -> None:
        """Test case for get_instance

        Get Instances of a ToolDefinition.
        """
        pass

    def test_get_instances(self) -> None:
        """Test case for get_instances

        Get Instances of a ToolDefinition.
        """
        pass


if __name__ == '__main__':
    unittest.main()
