# coding: utf-8

"""
    edu-sharing Repository REST API

    The public restful API of the edu-sharing repository.

    The version of the OpenAPI document: 1.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from edu_sharing_client.api.searchv1_api import SEARCHV1Api


class TestSEARCHV1Api(unittest.TestCase):
    """SEARCHV1Api unit test stubs"""

    def setUp(self) -> None:
        self.api = SEARCHV1Api()

    def tearDown(self) -> None:
        pass

    def test_get_metdata(self) -> None:
        """Test case for get_metdata

        get nodes with metadata and collections
        """
        pass

    def test_get_relevant_nodes(self) -> None:
        """Test case for get_relevant_nodes

        Get relevant nodes for the current user
        """
        pass

    def test_load_save_search(self) -> None:
        """Test case for load_save_search

        Load a saved search query.
        """
        pass

    def test_save_search(self) -> None:
        """Test case for save_search

        Save a search query.
        """
        pass

    def test_search(self) -> None:
        """Test case for search

        Perform queries based on metadata sets.
        """
        pass

    def test_search_by_property(self) -> None:
        """Test case for search_by_property

        Search for custom properties with custom values
        """
        pass

    def test_search_contributor(self) -> None:
        """Test case for search_contributor

        Search for contributors
        """
        pass

    def test_search_facets(self) -> None:
        """Test case for search_facets

        Search in facets.
        """
        pass

    def test_search_fingerprint(self) -> None:
        """Test case for search_fingerprint

        Perform queries based on metadata sets.
        """
        pass

    def test_search_lrmi(self) -> None:
        """Test case for search_lrmi

        Perform queries based on metadata sets.
        """
        pass


if __name__ == '__main__':
    unittest.main()
