# coding: utf-8

"""
    edu-sharing Repository REST API

    The public restful API of the edu-sharing repository.

    The version of the OpenAPI document: 1.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from edu_sharing_client.api.notificationv1_api import NOTIFICATIONV1Api


class TestNOTIFICATIONV1Api(unittest.TestCase):
    """NOTIFICATIONV1Api unit test stubs"""

    def setUp(self) -> None:
        self.api = NOTIFICATIONV1Api()

    def tearDown(self) -> None:
        pass

    def test_delete_notification(self) -> None:
        """Test case for delete_notification

        Endpoint to delete notification by id
        """
        pass

    def test_get_config2(self) -> None:
        """Test case for get_config2

        get the config for notifications of the current user
        """
        pass

    def test_get_notifications(self) -> None:
        """Test case for get_notifications

        Retrieve stored notification, filtered by receiver and status
        """
        pass

    def test_set_config1(self) -> None:
        """Test case for set_config1

        Update the config for notifications of the current user
        """
        pass

    def test_update_notification_status(self) -> None:
        """Test case for update_notification_status

        Endpoint to update the notification status
        """
        pass

    def test_update_notification_status_by_receiver_id(self) -> None:
        """Test case for update_notification_status_by_receiver_id

        Endpoint to update the notification status
        """
        pass


if __name__ == '__main__':
    unittest.main()
