# coding: utf-8

"""
    edu-sharing Repository REST API

    The public restful API of the edu-sharing repository.

    The version of the OpenAPI document: 1.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from edu_sharing_client.api.streamv1_api import STREAMV1Api


class TestSTREAMV1Api(unittest.TestCase):
    """STREAMV1Api unit test stubs"""

    def setUp(self) -> None:
        self.api = STREAMV1Api()

    def tearDown(self) -> None:
        pass

    def test_add_entry(self) -> None:
        """Test case for add_entry

        add a new stream object.
        """
        pass

    def test_can_access(self) -> None:
        """Test case for can_access

        test
        """
        pass

    def test_delete_entry(self) -> None:
        """Test case for delete_entry

        delete a stream object
        """
        pass

    def test_get_property_values(self) -> None:
        """Test case for get_property_values

        Get top values for a property
        """
        pass

    def test_search1(self) -> None:
        """Test case for search1

        Get the stream content for the current user with the given status.
        """
        pass

    def test_update_entry(self) -> None:
        """Test case for update_entry

        update status for a stream object and authority
        """
        pass


if __name__ == '__main__':
    unittest.main()
