name: publish

on:
  push:
    branches: 
      - develop
      - master
      - '**'
    tags: 
      - v[0-9]+.[0-9]+.[0-9]+

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - uses: actions/setup-python@v4
      with:
          python-version: '3.10'
    - name: Build Z-API
      run: pip3 install -r requirements.txt && ./generate-z-api.sh
    - uses: azure/docker-login@v1
      with:
        username: ${{ github.repository_owner }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - uses: rlespinasse/github-slug-action@v2.x
    - name: Build Z-API
      run: ./generate-z-api.sh
    - name: Build Docker image
      run: docker build --tag ${{ github.repository }}:${{ env.GITHUB_REF_SLUG }} .
    - name: Publish to DockerHub
      run: docker push ${{ github.repository }}:${{ env.GITHUB_REF_SLUG }}
